### ISSUE TITLE
Can't install on Kubuntu 19.10 with Inkscape from PPA

### ISSUE THREAD

**Issue by mfraser** [fablabnbg/inkscape-silhouette#100]
The Inkscape PPA has just released Inkscape 1.0 and now the inkscape-silhouette package won't install as:

dpkg: error processing archive /home/mfraser/Downloads/deb/inkscape-silhouette_1.22-1_all.deb (--unpack):
 trying to overwrite '/usr/share/inkscape/extensions/setup.py', which is also in package inkscape 1.0+r72~ubuntu19.10.1

**Comment by ottobot007** [comment]
I had to revert to 0.92 and have apt hold the package back at that version.

**Comment by t0b3** [comment]
usually `setup.py` files don't get packed up in deb packages, they contain mainly information about install and dependencies (what is already contained in `deb` files). I guess it shouldn't be in the inkscape package, neither be left installed after manual installation of inkscape-extension.

you may try and delete this file as a workaround...

**Comment by jnweiger** [comment]
Same on Ubuntu 18.04 -- it is an error to have a setup.py in the package. Deleting the file does not help on ubuntu. The installer knows that the file belongs to inkscape and would refuse to place anther one there, even if it were deleted before.

**Comment by t0b3** [comment]
@jnweiger I fixed `Makefile` to no longer include those odd `*.py` Files in deb
