### ISSUE TITLE
Registration marks do not work on Cameo 2

### ISSUE THREAD

**Issue by bianchifan** [fablabnbg/inkscape-silhouette#103]
System: Ubuntu Studio 19.10, Inkscape 0.92.5, inkcut-silhouette actual master

I serviced my MTB fork and due to a new frame I decided to spend it a couple of new sticker.
Worked out in inkscape I finally got the idea to cut them out via print&cut.
It was the very first time of try, so I took the reg...svg from examples, grouped all objects and copied them to a new layer turned right by 90° ( my layout was landscape).
Orginal layout, Fox 32 decals set.svg
[Fox 32 decals Set.zip](https://github.com/fablabnbg/inkscape-silhouette/files/4739953/Fox.32.decals.Set.zip)
A first test was done by printing ONLY the registration marks on a sheet of waste paper.
This sheet was put on a matte, two cutting layers made visible and the extention was started...
The result was ..hmmm
![DSC03414](https://user-images.githubusercontent.com/17491743/83943957-52bff680-a800-11ea-81e8-b97416eda519.JPG)
The objects were turned right another time and streched in two different scales..  :((
![DSC03415](https://user-images.githubusercontent.com/17491743/83944067-15a83400-a801-11ea-9bf4-4aa097970694.JPG)
![DSC03416](https://user-images.githubusercontent.com/17491743/83944069-193bbb00-a801-11ea-8213-695f789f97e0.JPG)

So I tried some work.
1st, I changed my sticker layout to portrait
New layout, Fox 32 decals set_portrait.svg
[Fox 32 decals Set_portrait.zip](https://github.com/fablabnbg/inkscape-silhouette/files/4739976/Fox.32.decals.Set_portrait.zip)

Then I started to build the extention with : python setup.py build
Doesn't run due to missed import files.
Next try with python3, received a couple of warnings, tried to install..unsuccessful.
But the folder "silhouette" was changed, in "__pycache__" *-37.pyc and *-38.pyc were found.
So I copied the complete folder to the inkscape extention.
Q&D I painted the reg marks on the clean backside of another sheet of waste paper and started the extention again with two visible cutting layers.
![Bildschirmfoto_2020-06-06_13-02-56](https://user-images.githubusercontent.com/17491743/83944777-68d0b580-a806-11ea-925f-8c31f287e923.png)

When the cut was done a message apeared..
![Bildschirmfoto_2020-06-06_12-28-54](https://user-images.githubusercontent.com/17491743/83944804-9a498100-a806-11ea-8b88-50994e119513.png)

Very strange result, I redrawed the cutted lines by hand to make them more shiny...
![DSC03417](https://user-images.githubusercontent.com/17491743/83944407-8bad9a80-a803-11ea-928d-ba749f3a0bca.JPG)
The orientation was right this time but streched/clipped in a different way.

When I yield up the reg marks I have my usual probs with positioning but the plot is done with correct dimensions.

BTW..here's  a view of ristretto's way of showing my svg

![Bildschirmfoto_2020-06-06_13-07-13](https://user-images.githubusercontent.com/17491743/83944642-6588fa00-a805-11ea-84c1-0810df9dacea.png)

**Comment by EtherGraf** [comment]
The warning "Unable to draw text 277mm" obviuously comes from a try to cut the regmarks layer. Plotting this layer is not needed.
The problem with the scaling has some other unknown reasons. Similar problems are reported with inkscape 1.0 and python3. 

Do you have some groups in your document? As a workaround you can try ungroup them.

Is the scaling correct at cuting without regmarks?

**Comment by bianchifan** [comment]
> The warning "Unable to draw text 277mm" obviuously comes from a try to cut the regmarks layer. 

For information only, I took the actual regmarks from this repository

>Plotting this layer is not needed.

??? How does the plotter know to use regmarks?
As I understood I have to send a docoment WITH regmarks to the plotter to mak it search for them...

> 
> Do you have some groups in your document? As a workaround you can try ungroup them.
> 
My svg is full of nested groups, I uploaded it...
>
> New layout, Fox 32 decals set_portrait.svg
> [Fox 32 decals Set_portrait.zip](https://github.com/fablabnbg/inkscape-silhouette/files/4739976/Fox.32.decals.Set_portrait.zip)
>

>
> Is the scaling correct at cuting without regmarks?
>
Yes, the scaling is correct, but not the offset (old prob for me but another story)
Cutting on waste paper, small one Ubunu 20.04/Inkscape 1.0, normal one Ubuntu 19.04/Inkscape 0.92.5

![DSC03419](https://user-images.githubusercontent.com/17491743/84380590-e110ef80-abe7-11ea-88b2-5aba6f9f0927.JPG)
![Bildschirmfoto_2020-06-11_13-39-26](https://user-images.githubusercontent.com/17491743/84381279-12d68600-abe9-11ea-8322-54e01b908a68.png)

**Comment by EtherGraf** [comment]
> ??? How does the plotter know to use regmarks?
> As I understood I have to send a docoment WITH regmarks to the plotter to mak it search for them...

The recognition of the regmarks is enabled on the ragmarks tab.
When enabled, the plotter device scans for the black lines printed on the paper. So it is not neccessary to send this layer to the plotter. BUT it is neccessary to set the correct four position/dimension values (given in the example) on this tab. With this information the plotter knows where the regmarkings are physically, where they should be logically from the document coordinates and can correct the differences.

This is how the extension works at the moment. The extension could be improved to recognize the regmark objects and its coordinates in the document by itself, but this is not done yet.

**Comment by bianchifan** [comment]
I'm sorry, it seems I was too lazy when reading the doc... Point 4....exclude the regmarks :(
I'll try this evening, THX for your help

**Comment by bianchifan** [comment]
Excluding the regmarks changed the game but didn't really help, rusults are not usable..
Wrong scaling and position vaying every plot.

1st example, 2 cutting layyers visible, regmarks not, regmarks switched on in plug, auto search
Regmarks on printout are a modified version from this git, no knife but red pen
![DSC03420](https://user-images.githubusercontent.com/17491743/84588236-f4110300-ae25-11ea-9d68-ba902592f1ce.JPG)
The black lines should be cutted but the plotter prefers the red path ;)

Next try, no auto, ref  set in plug instead -> no way, every time the plotter didn't find the marks :((
Roundabout 15 variations were tried.

Next ex:, regmarks are drawn manually at absolutely min positions due to Silhouette school.
distance  left, right, top -> 10mm, distance bottom -> ~16mm, line length ~ 6mm
Same as above, auto search for regmarks
![DSC03421](https://user-images.githubusercontent.com/17491743/84588585-f9bc1800-ae28-11ea-9f23-1bab28acd6c4.JPG)
2 tries, one with pen, one with knife for the plotter has problems to recognize the marks with open cover
- The vertical scaling seems to be  correct
- The positioning is catched from the  air, as I wrote in a former answer, Pos. for me not reproducable with regmarks switched on

For completion I tried twice with auto off and Distance  settings... marks not found.

Conclusion:
The marks in my document should be faulty, the mark bottom left is drawn much too close to the bottom.

To get use of my two printed sticker I switched the regmarks off and tried to position the paper carefully on the cutting mat, in my case I had to change the x-offset for -11.9 mm
![DSC03423](https://user-images.githubusercontent.com/17491743/84589050-5ec53d00-ae2c-11ea-8ac0-11e19c4ced4d.JPG)

Nearly perfect testcut
![DSC03424](https://user-images.githubusercontent.com/17491743/84589080-946a2600-ae2c-11ea-8657-7fc7a31ae7a9.JPG)

![DSC03426](https://user-images.githubusercontent.com/17491743/84589092-ac41aa00-ae2c-11ea-8fd5-faac53fffb59.JPG)

No problem changing the cutting layer and final cut without any test :)
![DSC03427](https://user-images.githubusercontent.com/17491743/84589123-e9a63780-ae2c-11ea-9914-5828d536722c.JPG)

While the first cut with recommanded pressure setting was partially too deep the pressure was slightly reduced, 18 instead of 20 for sticker paper -> perfect!

**Comment by bianchifan** [comment]
outdated
