### ISSUE TITLE
CAMEO 4 "sizing" problem

### ISSUE THREAD

**Issue by anthraxn8b** [fablabnbg/inkscape-silhouette#108]
Hi!
Great to have a plugin for inkscape!
It is running but I have a bunch of problems with it.

1. After sending to cameo 4 a popup shows a list of deprecation warnings. (sideshow problem)
2. The sizing does not match the representation in Inkscape. Example: A square with 100mm * 100mm converted to a path is 26.2mm * 26.2mm in reality (cutted) Changing the size (by mulipying 100mm * 3.82) gives me the exact same output as before (26.2mm * 26.2mm).

To get it running on my fedora 31 I had to:
1. Install the plugin by following the "Other Debian based Linux" route (download master archive & copy files)
2. Install pyusb
3. Create the file "/etc/udev/rules.d/99-graphtec-silhouette.rules" with the following content: "SUBSYSTEM=="usb", ATTR{idVendor}=="0b4d", ATTR{idProduct}=="1137", MODE="666""

Any idea what I am doing wrong?
(Setting the offset in mm seems to work!)

THX in advance!

**UPDATE 0**
When I directly create a square with 382mm * 382mm it results in a square of 100mm * 100mm!

**UPDATE 1**
After executing the "Apply Transforms" plugin BEFORE sending the data to the CAMEO 4 nearly workarounds my "sizing problem". So obviously the "transform matrix" is not taken into account by the plugin itself...
Now my problem is that the camao stops EXACTLY at the "correct" end of the page (inkscape setting is 21cm width).
So setting the offset and calculating the pages end seems to work.

**UPDATE 2**
Now I changed everything in Incscape to "IN"ch.
I am able to create a "drawing" that is 43 Inkscape-Inches (TM ;-) ) wide.
The real world mat would allow more than half an (real word) inch more...
I have an offset in the options dialog from 5mm on the X-axis and 15mm on the Y-axis which exactly points to 0/0 on the cutting mat.
This is all far away from beeing exact what really would be a nice "feature" ;-)

**SIDESHOW UPDATE - DEPRECATION WARNINGS**
sendto_silhouette.py:126: DeprecationWarning: inkex.localize was moved to inkex.localization.localize
  inkex.localize()	# 0.91
sendto_silhouette.py:270: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option('--active-tab', action = 'store', dest = 'active_tab',
sendto_silhouette.py:272: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option('-d', '--dashes',
sendto_silhouette.py:275: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option('-a', '--autocrop',
sendto_silhouette.py:278: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option('-b', '--bbox', '--bbox-only', '--bbox_only',
sendto_silhouette.py:281: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option('-c', '--bladediameter',
sendto_silhouette.py:284: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option('-C', '--cuttingmat', action = 'store',
sendto_silhouette.py:287: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option('-D', '--depth',
sendto_silhouette.py:290: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option('--dummy',
sendto_silhouette.py:293: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option('-g', '--strategy',
sendto_silhouette.py:297: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option('-l', '--sw_clipping',
sendto_silhouette.py:300: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option('-m', '--media', '--media-id', '--media_id',
sendto_silhouette.py:306: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option('-o', '--overcut',
sendto_silhouette.py:309: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option('-M', '--multipass',
sendto_silhouette.py:312: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option('-p', '--pressure',
sendto_silhouette.py:315: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option('-P', '--sharpencorners',
sendto_silhouette.py:318: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option('--sharpencorners_start',
sendto_silhouette.py:321: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option('--sharpencorners_end',
sendto_silhouette.py:324: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option('-r', '--reversetoggle',
sendto_silhouette.py:327: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option('-s', '--speed',
sendto_silhouette.py:330: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option( "-S", "--smoothness", action="store", type="float",
sendto_silhouette.py:332: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option('-t', '--tool', action = 'store',
sendto_silhouette.py:334: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option('-T', '--toolholder', action = 'store',
sendto_silhouette.py:336: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option('-V', '--version',
sendto_silhouette.py:339: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option('-w', '--wait', '--wait-done', '--wait_done',
sendto_silhouette.py:342: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option('-x', '--x-off', '--x_off', action = 'store',
sendto_silhouette.py:344: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option('-y', '--y-off', '--y_off', action = 'store',
sendto_silhouette.py:346: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option('-R', '--regmark',
sendto_silhouette.py:349: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option('--regsearch',
sendto_silhouette.py:352: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option('-X', '--reg-x', '--regwidth', action = 'store',
sendto_silhouette.py:354: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option('-Y', '--reg-y', '--reglength', action = 'store',
sendto_silhouette.py:356: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option('--rego-x',  '--regoriginx',action = 'store',
sendto_silhouette.py:358: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option('--rego-y', '--regoriginy', action = 'store',
sendto_silhouette.py:360: DeprecationWarning: Effect.OptionParser oder `optparse` ist veraltet und wurde durch `argparser` ersetzt.  `self.OptionParser.add_option` muss durch `self.arg_parser.add_argument` ersetzt werden. Die Argumente sind dabei ähnlich.
  self.OptionParser.add_option('-e', '--endposition', '--end-postition',
sendto_silhouette.py:1238: DeprecationWarning: Effect.affect heißt jetzt `Effect.run()`. Das Argument `output` wurde geändert.
  e.affect()
/home/boris/.config/inkscape/extensions/silhouette/Graphtec.py:433: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  resp = s.read(timeout=5000)
/home/boris/.config/inkscape/extensions/silhouette/Graphtec.py:549: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  resp = s.read(timeout=10000) # Large timeout because the plotter moves.
sendto_silhouette.py:991: DeprecationWarning: simpletransform.parseTransform -> Transform(str).matrix
  self.docTransform = parseTransform( 'scale(%f,%f)' % (sx, sy) )
sendto_silhouette.py:1031: DeprecationWarning: Effect.selected ist jetzt ein `dict`-Objekt der Klasse `SvgDocumentElement`. Stattdessen sollte `self.svg.selected` verwendet werden.
  self.recursivelyTraverseSvg( [self.selected[id]] )
sendto_silhouette.py:517: DeprecationWarning: simpletransform.composeParents -> elem.composed_transform() or elem.transform * Transform(mat)
  transform = composeParents(node, IDENTITY_TRANSFORM)
sendto_silhouette.py:518: DeprecationWarning: simpletransform.composeTransform -> Transform(M1) * Transform(M2)
  transform = composeTransform(self.docTransform, transform)
sendto_silhouette.py:519: DeprecationWarning: simpletransform.composeTransform -> Transform(M1) * Transform(M2)
  transform = composeTransform(extra_transform, transform)
sendto_silhouette.py:406: DeprecationWarning: simplepath.parsePath -> element.path.to_arrays()
  if len( simplepath.parsePath( d ) ) == 0:
sendto_silhouette.py:409: DeprecationWarning: cubicsuperpath.parsePath -> None
  p = cubicsuperpath.parsePath( d )
sendto_silhouette.py:412: DeprecationWarning: simpletransform.applyTransformToPath -> Path(path).transform(mat)
  applyTransformToPath( matTransform, p )
sendto_silhouette.py:215: DeprecationWarning: inkex.bezier.maxdist -> Get maximum distance within bezier curve
  if cspsubdiv.maxdist( b ) > flat:
sendto_silhouette.py:220: DeprecationWarning: inkex.bezier.beziersplitatt -> Split bezier at given time
  one, two = beziersplitatt( b, 0.5 )
/home/boris/.config/inkscape/extensions/silhouette/Graphtec.py:473: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  resp = s.read(timeout=1000)
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/dev/null' mode='w' encoding='UTF-8'>

**Comment by EtherGraf** [comment]
Which version of inkscape are you using?
Do you have any groupings in your document?

Seems a similar problem like in issue #101

**Comment by EtherGraf** [comment]
I think, you did nothing wrong, but the extension has some issues with inkscape 1.0

**Comment by anthraxn8b** [comment]
> Which version of inkscape are you using?

--> 1.0 (4035a4fb49, 2020-05-01)

> Do you have any groupings in your document?

--> Nope.

> Seems a similar problem like in issue #101

--> Maybe the root cause is the same...

**Comment by anthraxn8b** [comment]
> I think, you did nothing wrong, but the extension has some issues with inkscape 1.0

I do not know any kind of software that was not perfect or had major changes in version *.0 ;-)
Hopefully this will get fixed soon.

**Comment by igorangst** [comment]
I have the same problem with inkscape 1.0.1 (1.0.1+r73) and the latest checkout from github. The shapes cut by my Cameo3 are much smaller than the ones displayed in inkscape, approximately by a factor of 4.4. Any progress on this issue?

**Comment by igorangst** [comment]
Probably related to issue #101

**Comment by FlyingSamson** [comment]
I also just tested it using my most recent Cameo 4 branch (https://github.com/FlyingSamson/inkscape-silhouette/tree/cameo4-support) and could not reproduce the problem. 10x10cm square was plotted as expected. 
Is this still an issue?

Did you try creating a new Inkscape file or only tried opening existing ones, as there also were changes after 0.91 (I believe) changing the default dpi from 90 to 96. However, this would not account for a factor of 4.4...

Could you provide exact measurement within Inkscape and the cut object, e.g. of an rectangle (the larger the better) to determine the factor as exactly as possible?

**Comment by t0b3** [comment]
@igorangst @anthraxn8b you are welcome to retry with latest master branch and provide feedback or open new issues. Code is now expected to work with Inkscape 1.0.1 as well. The Cameo4 branch from FlyingSamson has been merged into master.

If the issue reappears provide the involved SVG file, this will help to track down the issue...
