### ISSUE TITLE
Dotted line cutting

### ISSUE THREAD

**Issue by stephanedaviet** [fablabnbg/inkscape-silhouette#11]
The Silhouette Studio software has the ability to cut in a dotted line way. I haven't found this ability through your – so great – extension. Do you know if it's something possible? If yes, I will certainly be ready to investigate on how to do that.

**Comment by protonenfalter** [comment]
The extension "convert2dashes" could be helpful here. It can be accessed from standard inkscape via Extensions > Modify Path > Convert to  Dashes (but maybe you need to set the language to english for it to show up).
The extension allows to convert a dashed path (which is a continuous line with an optical pattern in the first place and will be cut in a single stroke) to a path consisting of single dashes. The conversion obeys the pattern shown before, so you can fine-tune the dashing to your needs.
The converted path will be cut in distinct strokes and thus gives a "perforation". Please note that the extension can only modify paths (so e.g. not rectangles, but rectangles converted to paths).

Personally I prefer this functionality to be separate from the inkscape-silhouette extension (greater flexibility) but integration could probably done (convert2dashes is only about 70 lines of python).

**Comment by jnweiger** [comment]
I'll integrate that enhancement, if someone sends a patch.

**Comment by stephane-daviet-maif** [comment]
I'm not really versed in Python but could be a nice opportunity to get in it. Will get a look.
