### ISSUE TITLE
No backend available

### ISSUE THREAD

**Issue by sxwid** [fablabnbg/inkscape-silhouette#114]
I was running the extension with happiness until updating to Inkscape >1. Depreciation errors ok, but it freezes and tells me `No backend available`. I guess its a python2/python3 pyusb/libusb issue - can someone tell me which additional packages i need to install?

**Comment by Efenstor** [comment]
Actually the extension is currently left in the miserable shape. I also used it happily, then it all of a sudden got broken and what's even worse it seems no developer actually cares to restore it to its former glory. It's been seven months since the last update happened. Yes, it worked perfectly, and now it does not work at all. The fork from FlyingSamson does better but still absolutely unusable with my Portrait 2, it cuts some weird lines anywhere but where they should be. I see there are 7 pull requests in total, unfortunately I am no git expert and not much of a programmer, otherwise I'd be happy at least to try to apply all those patches to the clone of the repo myself (if there's a way to do it at all). But I am far from sure it would help. Someone should revive the work on this project, there is absolutely no replacement for it if you're using Linux. I currently resort to the stock Portrait Studio software in Windows installed in a virtual machine, and using that typical proprietary sluggish and awkward junk of a software is far from the smooth and practical experience I had with inkscape-silhouette :sigh:

**Comment by jnweiger** [comment]
:sigh: 
I have yet to write my first python3 inkscape 1.0 extension and then go
through the list of bitrotting extensions that I had created over the years
and see how they can be made compatible with inkscape 1.0 -- I have failed
to find the time for that during all the corona outages, so it is hard to
predict anything from my side. Sorry for neglecting this.
I've just invited @t0b3 to become maintainer here. More maintainers welcome (not only here)!
I no longer have any silhouette machines at home. That makes reviewing PRs harder, I guess.

**Comment by sxwid** [comment]
No hard feelings, I understand your problem completely. Since I am not very used to python, I think I am the wrong one, but as a betatester I might be of use :) And thanks for your great work so far!

**Comment by sxwid** [comment]
Issue solved: Inkscape 1.0.1 installed from snapcraft was unable to access libusb, even though it was allowed via permissions. Adding the inkscape repository and installing via apt solved the issue.

**Comment by t0b3** [comment]
@sxwid you are welcome to try the latest code from master and provide more feedback...

**Comment by Efenstor** [comment]
Yay! Confirmed: it's all working absolutely fine with Inkscape 1.0.1 in Debian Buster and Silhouette Portrait 2 via USB. I used registration marks with automatic search, and it works perfectly. Actually, the search for the registration marks in inkscape-silhouette always worked much better than in the proprietary Portrait Studio, and that's the first reason I stick to this extension (the second is that I'm primarily using Linux). The only tiny issue left is the setting of the AutoBlade depth, it does not work, but it didn't in all the previous releases, and frankly I don't really need it, so it doesn't bother me at all.

**Comment by t0b3** [comment]
@Efenstor thanks for reporting your valuable feedback. 
You could help out in testing the next big code changes introduced by merging Cameo4 support. I only ask you to check if the code still works with your Portrait2...
Can confirm this code https://github.com/FlyingSamson/inkscape-silhouette/tree/cameo4-support still works for your setup? - Thanks for reporting back.

**Comment by Efenstor** [comment]
> @Efenstor thanks for reporting your valuable feedback.
> You could help out in testing the next big code changes introduced by merging Cameo4 support. I only ask you to check if the code still works with your Portrait2...
> Can confirm this code https://github.com/FlyingSamson/inkscape-silhouette/tree/cameo4-support still works for your setup? - Thanks for reporting back.

Tested it now. It seems like it works fine but only with normal objects, if the objects are clones they are cut at the same positions as their sources.

**Comment by t0b3** [comment]
> > @Efenstor thanks for reporting your valuable feedback.
> > You could help out in testing the next big code changes introduced by merging Cameo4 support. I only ask you to check if the code still works with your Portrait2...
> > Can confirm this code https://github.com/FlyingSamson/inkscape-silhouette/tree/cameo4-support still works for your setup? - Thanks for reporting back.
> 
> Tested it now. It seems like it works fine but only with normal objects, if the objects are clones they are cut at the same positions as their sources.

@Efenstor thank you for your tests. Can you provide an example SVG to reproduce the cloning issue you got?

**Comment by Efenstor** [comment]
> > > @Efenstor thanks for reporting your valuable feedback.
> > > You could help out in testing the next big code changes introduced by merging Cameo4 support. I only ask you to check if the code still works with your Portrait2...
> > > Can confirm this code https://github.com/FlyingSamson/inkscape-silhouette/tree/cameo4-support still works for your setup? - Thanks for reporting back.
> > 
> > 
> > Tested it now. It seems like it works fine but only with normal objects, if the objects are clones they are cut at the same positions as their sources.
> 
> @Efenstor thank you for your tests. Can you provide an example SVG to reproduce the cloning issue you got?

Of course, here it is: https://yadi.sk/i/ol4Brxh1KAQkRg

**Comment by t0b3** [comment]
@Efenstor hmm, interesting. Can you execute `python sendto_silhouette.py --dummy=True stickers_v2_cut.svg` and provide the dump file `/tmp/silhouette.dump`?

**Comment by Efenstor** [comment]
@t0b3 Aha. Did it, here's the dump: https://yadi.sk/d/TW9xiTXucAhsHw

**Comment by Efenstor** [comment]
More info to consider: in Debian 9 /usr/bin/python is linked to python2, not python3. Here is the dump when the same command is run with python3: https://yadi.sk/d/8GFadoWVM1NAkA. And the stdout: https://yadi.sk/i/Nav9F5fe5xs19A

**Comment by t0b3** [comment]
> @t0b3 Aha. Did it, here's the dump: https://yadi.sk/d/TW9xiTXucAhsHw

Hmm, that's what your dump looks like with `python3 misc/read_dump.py <dumpfile>`
![image](https://user-images.githubusercontent.com/5751047/103458502-28d4a100-4d09-11eb-833d-240059cc763d.png)

**Comment by t0b3** [comment]
@Efenstor I understood your setup is Linux (Debian Buster) with Inkscape 1.0.1 + Python3.x and you are driving the tests with this branch https://github.com/FlyingSamson/inkscape-silhouette/tree/cameo4-support on Portrait2
Can you describe is only the first figure cut 6 times at the same position? Or is it just cut once and the remaining 5 are omitted? We need to further elaborate this behaviour...

**Comment by Efenstor** [comment]
@t0b3 You're correct about my setup, it's exactly that. As to the second stance: no, I have two first figures cut correctly, but then the second and the third pair is cut over the first pair. I dumped the first dump using just the "python" command, i.e. on my system it was done with python2, I guess that's why you rendered it with read_dump.py correctly. Try the second dump I sent, that was made with python3. Here is what I get when it's rendered with read_dump.py on my computer.
![Figure_1](https://user-images.githubusercontent.com/11175574/103459535-c0a2b100-4d42-11eb-83f5-a80e2cee6006.png)

**Comment by t0b3** [comment]
@FlyingSamson Can you double check [Efenstor's SVG](https://yadi.sk/i/ol4Brxh1KAQkRg) with PR #107 branch? and see if you get 2 or 6 figures cut?

**Comment by FlyingSamson** [comment]
I'm on it.

**Comment by Efenstor** [comment]
I tried the #107 branch now and it seems to work fine, all the cloned objects are cut at their places, both with or without the registration marks.

**Comment by FlyingSamson** [comment]
Yes seems to work just fine

**Comment by t0b3** [comment]
> I tried the #107 branch now and it seems to work fine, all the cloned objects are cut at their places, both with or without the registration marks.

@Efenstor help me trying to figure out what went wrong before. Was it a different branch that failed? If so, which one was it? I'd like to track this issue down...

**Comment by Efenstor** [comment]
@t0b3 I think it was my fault! I'm not too good at using GitHub and git in whole, I just followed your link https://github.com/FlyingSamson/inkscape-silhouette/tree/cameo4-support, clicked "Code" and copied the link to .git into the clipboard. Then ran _git clone https://github.com/FlyingSamson/inkscape-silhouette.git inkscape-silhouette-cameo4-support_ and didn't even noticed that I cloned the master branch. I presume I should switch to another branch after cloning and do _git fetch_, right?

Edit: hold on, it was a bit more complicated but I successfully switched the branches, now testing it.

**Comment by t0b3** [comment]
@Efenstor no worries... you may 
1. `git clone <repo>`
2. `git checkout <branch>`

so I presume the failing attempt was with https://github.com/FlyingSamson/inkscape-silhouette.git `master`
while the correct behaviour was observed with https://github.com/FlyingSamson/inkscape-silhouette.git `cameo4-support`, right?
...this would confirm PR  #107 delivers good results for you and there should be no worries to merge this PR.

**Comment by Efenstor** [comment]
I'm very sorry for all the mess. I confirm that the cameo4-support branch by FlyingSamson works just fine for me.
![Figure_1](https://user-images.githubusercontent.com/11175574/103461698-dddf7b80-4d52-11eb-950b-75611d9b0aff.png)

**Comment by t0b3** [comment]
> I'm very sorry for all the mess. I confirm that the cameo4-support branch by FlyingSamson works just fine for me.

Hooray, great to know it still works fine with Portrait2! - Thanks for your helpful feedback

**Comment by Efenstor** [comment]
> ...this would confirm PR #107 delivers good results for you and there should be no worries to merge this PR.

Yes, PR #107 works just fine, I followed the instructions on how to apply the commit which you provided there: https://github.com/fablabnbg/inkscape-silhouette/pull/107#issuecomment-753338032

**Comment by sxwid** [comment]
@t0b3 lots of work these days, I finally managed to test the masterbranch (download 3.1.21, 19.00) on Ubuntu 20.04.1 and my Silhouette Cameo 3. I tested with some random projects I often use - the following things work:

- [x] Regmarks (accuracy seems better [?!] over the whole A4 page)
- [x] Bounding Box
- [x] Repeat Stroke
- [x] Position after Cutting

but there is a problem with 
- [ ] Blade Depth (as mentionned by @Efenstor earlier). I had the feature working the uxwalters version, but only under special circumstances (couldnt reproduce today). Maybe some values get overridden by the Media Selection?!
- [x] convert to dashes gives me the following warning: `convert2dashes.py:59: DeprecationWarning: simplestyle.parseStyle -> dict(inkex.Style.parse_str(s))
  style = simplestyle.parseStyle(node.get('style'))
`
Thanks for all the work, maybe this helps a little? If I should test a specific thing, I'd be happy to!

**Comment by t0b3** [comment]
@sxwid it would help a lot if you can track down which version from uxwalter had Blade Depth working. @uxwalter what is your guess on that?
... and true: convert2dashes wasn't on my radar until now.
your help is very welcome to
- [x] write a unit test with this parameter
- [x] help out in porting to Inkscape 1.0 API

**Comment by sxwid** [comment]
@t0b3 I am afraid, but maybe you overestimate my IT skills. I have no clue how to attack these tasks professionally :-o. 
Good news regarding the Autoblade Issue: It is working in the current version, but you have to set the Tool to "Autoblade" (not "Cut" as per default). But: The function could use some improvement: For example a memory of the last setting, that it doesn't set the blade every time you cut again.

**Comment by uxwalter** [comment]
> @uxwalter what is your guess on that?

No idea. In theory nothing I touched should affect this other than the refactor that reads values from the inkscape-rendered options window. There's no processing after that until the .pen and .autoblade members are consumed by SilhouetteCameo.setup(). I walked through a few examples with a debugger and the options seem to be processed and passed on correctly. If it's still broken I'd  be happy to take a look provided someone can point me to a misbehaving .svg and corresponding options.

**Comment by sxwid** [comment]
> Good news regarding the Autoblade Issue: It is working in the current version, but you have to set the Tool to "Autoblade" (not "Cut" as per default).

Maybe not highlighted enough - I guess its rather a UX / UI Design Issue...

**Comment by sxwid** [comment]
#

**Comment by Efenstor** [comment]
AutoBlade still does not work for Portrait 2. No matter the tool selected.

**Comment by sxwid** [comment]
> AutoBlade still does not work for Portrait 2. No matter the tool selected.
Does it change if you set the media to Custom?
![grafik](https://user-images.githubusercontent.com/13117378/104106125-96597200-52b3-11eb-8877-1f1e3fca2297.png)

**Comment by Efenstor** [comment]
@sxwid No, it doesn't help. It actually never worked for me. I am not sure how it's supposed to work with the other Silhouette machines but with Portrait 2, with the stock software, it just pushes the blade down again and again over the slot near the left edge of the plotting area until the blade is set to the needed position. May be inkscape-silhouette expects it to be set in another fashion? Also, how the printer gets the current blade position, at least to start counting from is a mystery to me, there seems to be no special sensor for that.

**Comment by sxwid** [comment]
@Efenstor In my understanding, this is how autoblade sets the depth: It uses the two cutouts at the left of the initial position of the tool slide (see red circle in the middle image). First, the the blade is set to zero by pushing down 9 times in the hole at the left. The two cams (left and right of autobladetool, green circle) prevent that the blade is pushed further than shown in the picture on the left. It will stay at 0 even if you continue pushing down. There you have your defined zeroing of the blade. 
After that you change to the rectangular cutout where the cams fit in and push down the desired blade depth. 
![autoblade](https://user-images.githubusercontent.com/13117378/104121560-82f3e880-533f-11eb-83ae-f423a7f69e19.png)


The Cameo has support for two tools, autoblade is only possible in the left toolholder, maybe there is the issue with portrait 2?

**Comment by Efenstor** [comment]
@sxwid Ah, now I see! The AutoBlade switch actually has two modes of operation: half-way and fully pressed. The protrusions limit the depth so that it's pressed half-way. In the half-way mode it goes down to zero and stays at that position, and when it's fully pressed the cycle is looped.

This is how the switching area looks in Portrait 2:
![P1104582](https://user-images.githubusercontent.com/11175574/104122244-78a11100-5376-11eb-9f93-0d7c05aa7e6f.JPG)
As you can see, there is no separate hole for the half-way switching, so I presume it must be done simply at the right edge of the elongated hole; this way, of course, only one of the protrusions is used, but I tested and it does the job fine.

Here is the picture of the Portrait 2 switching hole. The ruler is in centimeters.
![P1104583](https://user-images.githubusercontent.com/11175574/104122513-f6195100-5377-11eb-93d7-b55d79364fb2.JPG)

**Comment by sxwid** [comment]
@Efenstor so you could fix the code for Portrait? Glad I could light up the dark field of the Autoblade Setting :-)

**Comment by Efenstor** [comment]
@sxwid Code? No. Unfortunately I am no Python programmer.
