### ISSUE TITLE
Remove eggbot_hatch from this extension

### ISSUE THREAD

**Issue by EtherGraf** [fablabnbg/inkscape-silhouette#122]
I was just irritated, why my eggbot_hatch extension got overwritten with an older release recently. 
Investigation showed me, that this comes from installing the recent version of this extension inkscape_silhouette. Here are the files eggbot_extension.inx and eggbot_hatch.py included. 

As far I can see from history, these was only examples for extensions. 
I cannot see any use in the silhouette plotter extension for hatching. 

@jnweiger Can we remove these files?
If not, then we should at least rename it, for not conflicting with the eggbot extension.

**Comment by t0b3** [comment]
@EtherGraf thanks for your hint. removed from master now.

**Comment by t0b3** [comment]
@jnweiger hope this is ok for you too - if not, we can still revert... just give me a hint
