### ISSUE TITLE
Incorrect extensions folder for Mac

### ISSUE THREAD

**Issue by jtebert** [fablabnbg/inkscape-silhouette#126]
I'm installing the extension on Mac OS 11.1 (Big Sur) and Inkscape 1.0.1, and this has the incorrect extensions path hard-coded into the installer script. (I haven't tried this on an older version of Mac to know if this is a new problem or carries over from older versions of Mac OS.)

In `install_osx.py`, the `extensions_dir` is set as:
```python
extensions_dir = os.path.join(os.path.expanduser("~"), ".config", "inkscape", "extensions")
```

However, within the Inkscape (1.0.1) preferences, the extension directory is listed as:
```
/Applications/Inkscape.app/Contents/Resources/share/inkscape/extensions
```

As a result, the install script does not produce an error, but (of course) the extension doesn't appear in Inkscape. If I change the extensions directory to the one listed in Inkscape, I'm able to install it.

Is there a way for the extension to pull the directory from Inkscape more directly so that it will have the correct location?

**Comment by t0b3** [comment]
I'd be interesting to know what Inkscape 1.0+ on OSX tells about user defined extensions...
what path is shown at menu Edit > Preferences > System > User extensions? - see https://wiki.inkscape.org/wiki/index.php?title=File:Open_folders_from_preferences.png

Further I'm curious to see if the extension would be correctly recognized if you place at _user extensions_ path...

**Comment by tschamm** [comment]
I installed the extension on Mac OS 11.2 (Big Sur) with Inkscape 1.0.2, for me the correct Install Folder on OS 11 is:
```
~/Library/Application Support/org.inkscape.Inkscape/config/inkscape/extensions
```
This is also the path given, when opening the Inkscape Settings -> System -> User settings.

@jtebert Can you check if this is valid for you too?
