### ISSUE TITLE
No backend available

### ISSUE THREAD

**Issue by LCortes-PT** [fablabnbg/inkscape-silhouette#129]
Thank you for your software. I used it on ubuntu 18.04 and worked like a charm.
Now, I upgraded to ubuntu 20.04 and inkscape 1.0.
Installed sent to silhouette and found first problem: the extensions aren't in /usr/share/inkscape/ extensions, but are in /snap/inkscape/8049/share/inkscape/extensions. I tryed to copy files to this directory but with no sucess, so I put the extensions in ~/.config/inkscape/extensions and they already appear in extensions menu in inkscape.
The problem is, when I try to "send to silhouette" there is an error box with message: "No backend available"

Phyton3-usb is installed, and silhouette is installed as well, as a generic text-only printer.

What I'm doing wrong?

**Comment by EuphoricPenguin** [comment]
This is the case for me as well. I'm on Windows 10, and I followed the instructions listed in the README to a tee. Everything seemed to go smoothly, but this is the only thing that seems to stand in the way.

**Comment by EuphoricPenguin** [comment]
I actually managed to get past this by installing the libusb-win32 package, at least for Windows. Now I'm stuck where it doesn't recognize my machine. I opened a new issue because of this.

**Comment by t0b3** [comment]
it seems you installed the snap package :-1: 

what happens if you follow [the instructions](https://github.com/fablabnbg/inkscape-silhouette#ubuntu-1804-or-2004)?

**Comment by LCortes-PT** [comment]
I had installed snap edition.
Following the instructions every thing works smooth.
Thank you
