### ISSUE TITLE
Install using .deb not working on Ubuntu 20.04 with inkscape 1.02

### ISSUE THREAD

**Issue by concretedog** [fablabnbg/inkscape-silhouette#130]
First of all, many thanks for  your work this amazing extension, its a fabulous tool. 

Following the instructions for install on ubuntu 20.04 I downloaded the .deb (having installed python3 -usb) and installed and it didn't work/appear in inkscape 1.02. I resolved this by following the later install for other debian based distros and manually unzipping and adding the folder and two files to .config/inkscape/extensions, works perfectly now. 

Thanks again.

**Comment by t0b3** [comment]
@concretedog did you get any error messages? or did the deb install correctly? [need more info] 
what would need to be changed? 
please feel free to make a PR...

**Comment by concretedog** [comment]
So I tired to install using the instructions on the readme and double clicked the downloaded .deb, it launched into the Ubuntu Software application and appeared to install correctly, no error messages, then opening inkscape there was no sign of the extension, using the other method of copy pasting from the downloaded zip worked though. I am definitely not skilled enough to make a PR :) Just wanted to feedback my experience so fee free to close.

**Comment by t0b3** [comment]
a) what is the output of `dpkg -L inkscape-silhouette | grep /usr/share/inkscape/extensions/`?
b) which directory is in Inkscape `Menu -> Edit -> Preferences -> System -> Inkscape extensions`?

**Comment by concretedog** [comment]
The output of dpkg is 
`/usr/share/inkscape/extensions/sendto_silhouette.inx
/usr/share/inkscape/extensions/sendto_silhouette.py
/usr/share/inkscape/extensions/silhouette
/usr/share/inkscape/extensions/silhouette/Geometry.py
/usr/share/inkscape/extensions/silhouette/Graphtec.py
/usr/share/inkscape/extensions/silhouette/Strategy.py
/usr/share/inkscape/extensions/silhouette/StrategyMinTraveling.py
/usr/share/inkscape/extensions/silhouette/__init__.py
/usr/share/inkscape/extensions/silhouette/__pycache__
/usr/share/inkscape/extensions/silhouette/__pycache__/Geometry.cpython-38.pyc
/usr/share/inkscape/extensions/silhouette/__pycache__/Graphtec.cpython-38.pyc
/usr/share/inkscape/extensions/silhouette/__pycache__/Strategy.cpython-38.pyc
/usr/share/inkscape/extensions/silhouette/__pycache__/StrategyMinTraveling.cpython-38.pyc
/usr/share/inkscape/extensions/silhouette/__pycache__/__init__.cpython-38.pyc
/usr/share/inkscape/extensions/silhouette/__pycache__/convert2dashes.cpython-38.pyc
/usr/share/inkscape/extensions/silhouette/beutil.py
/usr/share/inkscape/extensions/silhouette/convert2dashes.py
/usr/share/inkscape/extensions/silhouette/pyusb-1.0.2
/usr/share/inkscape/extensions/silhouette/pyusb-1.0.2/usb
/usr/share/inkscape/extensions/silhouette/pyusb-1.0.2/usb/__init__.py
/usr/share/inkscape/extensions/silhouette/pyusb-1.0.2/usb/__init__.pyc
/usr/share/inkscape/extensions/silhouette/pyusb-1.0.2/usb/_debug.py
/usr/share/inkscape/extensions/silhouette/pyusb-1.0.2/usb/_debug.pyc
/usr/share/inkscape/extensions/silhouette/pyusb-1.0.2/usb/_interop.py
/usr/share/inkscape/extensions/silhouette/pyusb-1.0.2/usb/_interop.pyc
/usr/share/inkscape/extensions/silhouette/pyusb-1.0.2/usb/_lookup.py
/usr/share/inkscape/extensions/silhouette/pyusb-1.0.2/usb/_lookup.pyc
/usr/share/inkscape/extensions/silhouette/pyusb-1.0.2/usb/_objfinalizer.py
/usr/share/inkscape/extensions/silhouette/pyusb-1.0.2/usb/_objfinalizer.pyc
/usr/share/inkscape/extensions/silhouette/pyusb-1.0.2/usb/backend
/usr/share/inkscape/extensions/silhouette/pyusb-1.0.2/usb/backend/__init__.py
/usr/share/inkscape/extensions/silhouette/pyusb-1.0.2/usb/backend/__init__.pyc
/usr/share/inkscape/extensions/silhouette/pyusb-1.0.2/usb/backend/libusb0.py
/usr/share/inkscape/extensions/silhouette/pyusb-1.0.2/usb/backend/libusb0.pyc
/usr/share/inkscape/extensions/silhouette/pyusb-1.0.2/usb/backend/libusb1.py
/usr/share/inkscape/extensions/silhouette/pyusb-1.0.2/usb/backend/libusb1.pyc
/usr/share/inkscape/extensions/silhouette/pyusb-1.0.2/usb/backend/openusb.py
/usr/share/inkscape/extensions/silhouette/pyusb-1.0.2/usb/backend/openusb.pyc
/usr/share/inkscape/extensions/silhouette/pyusb-1.0.2/usb/control.py
/usr/share/inkscape/extensions/silhouette/pyusb-1.0.2/usb/control.pyc
/usr/share/inkscape/extensions/silhouette/pyusb-1.0.2/usb/core.py
/usr/share/inkscape/extensions/silhouette/pyusb-1.0.2/usb/core.pyc
/usr/share/inkscape/extensions/silhouette/pyusb-1.0.2/usb/legacy.py
/usr/share/inkscape/extensions/silhouette/pyusb-1.0.2/usb/legacy.pyc
/usr/share/inkscape/extensions/silhouette/pyusb-1.0.2/usb/libloader.py
/usr/share/inkscape/extensions/silhouette/pyusb-1.0.2/usb/libloader.pyc
/usr/share/inkscape/extensions/silhouette/pyusb-1.0.2/usb/util.py
/usr/share/inkscape/extensions/silhouette/pyusb-1.0.2/usb/util.pyc
/usr/share/inkscape/extensions/silhouette_multi.inx
/usr/share/inkscape/extensions/silhouette_multi.py
`

**Comment by concretedog** [comment]
Ah the inkscape extensions are here via the preferences - system path
`/snap/inkscape/8746/share/inkscape/extensions`

**Comment by t0b3** [comment]
snap packages won't work without adapting the preferences

**Comment by twmr** [comment]
So, you've installed inkscape using a snap pkg, but the extension using a deb pkg. I don't think that it makes sense that this is supported by the `inkscape-silhouette` deb pkg. We could create a separate snap pkg for it, but I think we should avoid that.
