### ISSUE TITLE
No Graphtec Silhouette devices found

### ISSUE THREAD

**Issue by EuphoricPenguin** [fablabnbg/inkscape-silhouette#133]
```
No Graphtec Silhouette devices found.
Check USB and Power.
Devices: 
```
This is the error I get when I click "Apply." I am not entirely sure what this is all about, since I did have to go out of the way of the README instructions and install the driver mentioned in the wiki instructions (which happen to be completely different). I am aware that the original Cameo model doesn't like 3.0/3.1 ports, so I have it plugged into my sole 2.0 port on this Windows 10 machine.

**Comment by t0b3** [comment]
looks like a communication setup issue. you may try https://github.com/fablabnbg/inkscape-silhouette/issues/61#issuecomment-381375567 these instructions to test your setup. beware to use [the productID corresponding to your plotter](https://github.com/fablabnbg/inkscape-silhouette/blob/master/silhouette/Graphtec.py#L119-L126).
