### ISSUE TITLE
examples/testcut_sq_tr.py needs updating

### ISSUE THREAD

**Issue by gwhitney** [fablabnbg/inkscape-silhouette#151]
As noted in the discussion to #147, examples/testcut_sq_tr.py needs to be updated because of recent changes; it uses at least one option that is no longer current. I am happy to do this, since I made the breaking changes. But I am not seeing much in the way of documentation of this file: Is this supposed to cut vinyl? is the way to run this simply to go to the distribution directory and execute `python3 examples/testcut_sq_tr.py` ?

If you could give me just a quick pointer, I will get it working again. Also, is there any place I should check in a little bit of documentation for this program? Thanks!

**Comment by t0b3** [comment]
@EtherGraf any hints on how you used this or prefer to work in the future or to be documented?

**Comment by EtherGraf** [comment]
I have never used this utilities for myself. I think they are just some basic first examples how to use the graphtec lib. If anyone can use it for some automated calibration cuts then this is fine, but i am not sure if this was the intended use case.

**Comment by t0b3** [comment]
@jnweiger can you give @gwhitney a hint for which cases `examples/testcut_sq_tr.py` is meant to work?
