### ISSUE TITLE
Unable to use extension due to button being greyed out

### ISSUE THREAD

**Issue by AmEv7Fam** [fablabnbg/inkscape-silhouette#153]
I'm unable to use the extension with either a Silhouette Cameo 1 or Silhouette SD 1 on Windows due to the drop-down menu option being greyed out. 

![image](https://user-images.githubusercontent.com/1711170/125178784-392c7380-e1a5-11eb-9cfc-6f7513bf5b04.png)

Windows 10 21h1, Inkscape 1.0.

**Comment by t0b3** [comment]
Thanks for reporting your issue. Looks like the extension isn't in the [right place](https://inkscape.org/forums/questions/extension-greyed-out-tried-everything-help/#c21083).
Can you double check you followed the steps according to [this instructions](https://github.com/fablabnbg/inkscape-silhouette/blob/master/README.md#silhouette-inkscape-extension-itself)

**Comment by AmEv7Fam** [comment]
That's exactly what I did wrong!

![image](https://user-images.githubusercontent.com/1711170/125202789-6a9f5080-e232-11eb-9fa3-e88172125d26.png)

I think the instructions may have been updated since I last tried, as it's a lot more clear now.
