### ISSUE TITLE
Status of "multi action" variant of plugin?

### ISSUE THREAD

**Issue by gwhitney** [fablabnbg/inkscape-silhouette#155]
I was just trying to set up a quick way to install the extension just for my user account in Linux (for testing during development work) and discovered that there already is an undocumented `make install_local` that does this. Excellent. But then I noticed that it also installs a "Silhouette Multi Action" variant of the plugin as well.

This variant does not seem to be documented anywhere, although it is mentioned in one issue, #70. As near as I can guess, it seems maybe that it is intended to allow different parameters for different color strokes in the SVG file. As I often want to score and cut in one pass, I would totally use such a feature.

But even after `make install_local` (from current HEAD), the "Silhouette Multi Actions..." extension doesn't do anything except put up a dialogue with a "dry run" checkbox and "Cancel" and "Apply" buttons. Hitting "Apply" just causes an alarm ding, with no display or activity. So the extension seems broken? Any thoughts on the feasibility and desirability of restoring it?

I will give it a bit of a try now since this would be a very useful feature for me, but if anyone reading this has thoughts or guidance on getting silhouette_multi working again, I'd appreciate hearing.

**Comment by EtherGraf** [comment]
I think you should have a look at Pull request #45 There is a discussion abut this feature. 
I think it should work so far, but you are missing some requirements. Not 100% sure about the state of it.

**Comment by gwhitney** [comment]
Turns out that there was no way that silhouette_multi as it stood was going to work with Inkscape 1.0 or later. So just filed a PR to get it up to speed.
