### ISSUE TITLE
More inclusive name for primary branch?

### ISSUE THREAD

**Issue by gwhitney** [fablabnbg/inkscape-silhouette#160]
There seems to be a sort of open-source-community-wide movement to change the name of the primary branch of projects to "main" in an effort to keep computer science terminology as inclusive as possible. Would you take the step of doing so? Thanks for considering it.

**Comment by t0b3** [comment]
Can you provide a PR with the necessary changes for CI, README, etc.? This would be great...

**Comment by gwhitney** [comment]
OK, I think/hope that #161 has everything you need... thanks so much for your openness to a change of this nature!

**Comment by gwhitney** [comment]
Thanks for merging and renaming the primary branch!
