### ISSUE TITLE
Unclear which number the blade should be set to

### ISSUE THREAD

**Issue by probonopd** [fablabnbg/inkscape-silhouette#18]
Thanks for this great plugin!

When using this software it is unclear which number the blade should be set to. The original software displays a number which the blade should be set to physically.

![bildschirmfoto vom 2016-01-23 21-02-01](https://cloud.githubusercontent.com/assets/2480569/12532437/97649e66-c214-11e5-9cb8-75aedd00a9a7.png)

**Comment by probonopd** [comment]
Similarly, it would be nice to see the media defaults for speed and pressure (depending on the selected medium) rather than "0".

**Comment by iromero91** [comment]
Unfortunately, due to Inkscape's current extension architecture it's impossible to make one element in the GUI respond to changes in the other, it's just a static form that pipes the data through a shell script and reads the result.

**Comment by probonopd** [comment]
Thanks @iromero91 
Then maybe a "help" button with a static text or table would be helpful. Or a dropdown menu saying "Vinyl (Blade 2)" or something like that?
Currently I am hesitant to even try this software because I don't want to damage the blade or cutter by using wrong settings.

**Comment by jnweiger** [comment]
The inkscape user interface is really limiting, that is true.
We could add the Blade setting number to the dropdown menue of the material parameters, though.

**Comment by probonopd** [comment]
Now that there is a dropdown, why can't it say **"Silhouette Vinyl (set blade to 2)"**?

In other words, a) have the same media types as the original software and b) tell the user what to set the blade to.

![screenshot from 2016-05-15 19 26 31](https://cloud.githubusercontent.com/assets/2480569/15275701/19358e48-1ad3-11e6-8740-fee31bb05372.png)

While we are at it, it would also be great if Speed and Pressure would not show 0 but the actual media default. This would make it less risky to fine-tune them.

**Comment by jnweiger** [comment]
@probonopd inkscape cannot update GUI elements dynamically. I've added [P=..., S=...] prefixes to all the menue entries, so that you know the values you are using.

The blade settings always need some experimentation. I often use 2 or 3 with thermo transfer foils or adhesive sticker foils.

**Comment by probonopd** [comment]
Thanks!

Just for reference, I found the following post which was very helpful for me:
https://www.facebook.com/SilhouetteCameo.UK/posts/698156140267966
1. Take a sheet of the media you are trying to cut and fold it in half.
2. Take the blade out of the machine, set it to 1 and hold it in your hand as you would a pen but held vertically as it would be in the machine.
3. Get your folded media and with your blade held like a pen but kept vertically press firmly down on the media and 'draw' a line.
4. Next have a look at the media; with the correct setting you should have just cut a line through the top layer of the folded card without cutting in to the back layer. If you have not cut through the media, increase the blade by 1 position and repeat from step 3.
5. Keep doing this until you reach the correct setting to cut the top layer without cutting the back. 
6. Once this is done the blade can be put back in to the machine.

Perhaps it would help others to put this somewhere in the help.

**Comment by jnweiger** [comment]
Great instruction. I am adding the instructions as another 'Blade Setting' tab. Thank you for sharing!
