### ISSUE TITLE
usb.core missing (and other windows issues)

### ISSUE THREAD

**Issue by JLiver** [fablabnbg/inkscape-silhouette#2]
Hi there

I've tried to follow your installation instructions on a Windows 7 64-bit machine. 

On this line:
Download and install http://sourceforge.net/projects/libusb-win32/files/libusb-win32-releases/ *\* x86\libusb0_x86.dll: x86 32-bit library. Must be renamed to libusb0.dll On 64 bit, Installs to Windows\syswow64\libusb0.dll. On 32 bit, Installs to Windows\system32\libusb0.dll. *\* X86 ONLY ARCHITECTURES: x86\libusb0.sys: x86 32-bit driver. Installs to Windows\system32\drivers\libusb0.sys

When I install I get a number of options. I chose the printer option and the file "Windows\syswow64\libusb0.dll" correctly installed

Then this line:
cd C:\Python27\Lib\pyusb-1.0.0b1 \Python27\python.exe setup.py install

I did not have Python installed, so I installed the latest stable version. It didn't have a folder/directory called "pyusb"

I'm not familiar with Python, so not sure how to install the right files.

Just in case it wasn't an issue, I tried to run an export to Silhouette and got this message:

Traceback (most recent call last):
  File "sendto_silhouette.py", line 81, in <module>
    from silhouette.Graphtec import SilhouetteCameo
  File "C:\Program Files (x86)\Inkscape\share\extensions\silhouette\Graphtec.py", line 10, in <module>
    import usb.core
ImportError: No module named usb.core

How do I get the usb.core module loaded?

**Comment by jnweiger** [comment]
Thanks for testing!

I found that the README.md and the wiki page were inconsistent.
Both try to describe the installation procedure. Made them consistent. 

Not sure about choosing the printer option either.

From your report, I take it, that we need instructions for installing pyusb, which is also hosted on sourceforge.
I made something up. Please test.

**Comment by JLiver** [comment]
Hi Jurgen

No problem! Here's where I'm at.

Python was installed with Inkscape
"Not sure about choosing the printer option either." - this is a dialog box you get with the .exe version of libusb. I don't think it matters.

I extracted pyusb to c:\pyusb-1.0.0b1

I opened a DOS window as an administrator and typed in
cd c:\pyusb-1.0.0b1

then
"C:\Program Files (x86)\Inkscape\python\python.exe" setup.py install

The install wouldn't work because python26.dll was missing.
I moved python26.dll from C:\Program Files (x86)\Inkscape to C:\Program Files (x86)\Inkscape\python

I ran the install again and  pyusb installed correctly - at least there were no errors reported.

I opened Inkscape, added some objects and ran the extension. I got the following message this time:

Traceback (most recent call last):
  File "sendto_silhouette.py", line 991, in <module>
    e = SendtoSilhouette()
  File "sendto_silhouette.py", line 202, in **init**
    self.tty = open("/dev/null", 'w')
IOError: [Errno 2] No such file or directory: '/dev/null'

I think that there might be some hardcoded directories in there.

cheers

Jason

**Comment by jnweiger** [comment]
Congrats, you are getting to the point, where I feel more competent now. 
That is good :-) Please pull and try the latest:

commit 7da47c27561a0dc1977643afc90219fd4dc7b5ae
    found os.devnull instead of hardcoded '/dev/null'

BTW: would you like to improve the instructions on the wiki yourself?

**Comment by JLiver** [comment]
Cheers :) here's the next message:

  File "sendto_silhouette.py", line 4
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

No probs with instructions, I'll do them when this is finished if you like.

**Comment by jnweiger** [comment]
oops, now your sendto_silhouette.py is corrupt. Did I do that?
Please double check, that the file wasn't copied over with some html or wiki contents.

**Comment by JLiver** [comment]
Ah, Firefox was somehow converting the .py file into an HTML document. Here's the next message. Similar to the last one but a different folder.:

Traceback (most recent call last):
  File "sendto_silhouette.py", line 994, in <module>
    e.affect()
  File "C:\Program Files (x86)\Inkscape\share\extensions\inkex.py", line 215, in affect
    self.effect()
  File "sendto_silhouette.py", line 918, in effect
    o = open(self.dumpname, 'w')
IOError: [Errno 2] No such file or directory: '/tmp/silhouette.dump'

I've been using the dummy device option while we've been testing.

**Comment by JLiver** [comment]
I've just done a test as follows:

The Silhouette was plugged into the USB port and switched on
Inkscape started.
Export to the actual cutter, instead of dump, and I'm getting the message:

No Graphtec Silhouette devices found.
Check USB and Power.

I also checked with Silhouette Studio and it cut the card ok.

**Comment by jnweiger** [comment]
next commit, please pull cff4d668b09427d0e861668a65fbb2c4780f0f2a

fixing usage of /tmp/, added debugging help,
    giving usb.core.find() a try on windows

And yes, please add your findings to the wiki install instructions, eventually.

**Comment by JLiver** [comment]
Hi there

I did the test to dump first, and received the following message:

dump written to  c:\users\jason\appdata\local\temp\silhouette.dump  ( 55  points )

So that looks like it's working :)

When I do the test to the cutter, I get the following message:

No Graphtec Silhouette devices found.
Check USB and Power.
Devices: 

There aren't any devices listed.

Just to check, the libusb0.dll file has an internal version number F i l e V e r s i o n     1 . 2 . 6 . 0   8 and is in C:\Windows\SysWOW64

cheers

Jason

**Comment by JLiver** [comment]
Just to add an extra bit of information, I read the instructions on libusb, and ran the inf-wizard program which created an inf file. 

I then tried send some cuts to Silhouette, and it worked. 

When I sent it a second time, I got the following error:

Traceback (most recent call last):
  File "sendto_silhouette.py", line 997, in <module>
    e.affect()
  File "C:\Program Files (x86)\Inkscape\share\extensions\inkex.py", line 215, in affect
    self.effect()
  File "sendto_silhouette.py", line 930, in effect
    pressure=self.options.pressure, speed=self.options.speed)
  File "C:\Program Files (x86)\Inkscape\share\extensions\silhouette\Graphtec.py", line 294, in setup
    s.initialize()
  File "C:\Program Files (x86)\Inkscape\share\extensions\silhouette\Graphtec.py", line 263, in initialize
    s.write("\x1b\x04")
  File "C:\Program Files (x86)\Inkscape\share\extensions\silhouette\Graphtec.py", line 230, in write
    raise ValueError('write %d bytes failed: r=%d' % (len(chunk), r))
ValueError: write 2 bytes failed: r=0

I then removed the card and reinserted it into the cutter. I stopped and started Inkscape.

The cutter then ran the card backwards and forwards a couple of times. It then cut the shapes that I drew, and finally gave the following error:

Traceback (most recent call last):

  File "sendto_silhouette.py", line 997, in <module>

```
e.affect()
```

  File "C:\Program Files (x86)\Inkscape\share\extensions\inkex.py", line 215, in affect

```
self.effect()
```

  File "sendto_silhouette.py", line 961, in effect

```
state = dev.status()
```

  File "C:\Program Files (x86)\Inkscape\share\extensions\silhouette\Graphtec.py", line 251, in status

```
s.write("\x1b\x05")
```

  File "C:\Program Files (x86)\Inkscape\share\extensions\silhouette\Graphtec.py", line 230, in write

```
raise ValueError('write %d bytes failed: r=%d' % (len(chunk), r))
```

ValueError: write 2 bytes failed: r=0

Then I tried again
 without removing the card and reinserting it. The cutter didn't move and I got the following error:

Traceback (most recent call last):

  File "sendto_silhouette.py", line 997, in <module>

```
e.affect()
```

  File "C:\Program Files (x86)\Inkscape\share\extensions\inkex.py", line 215, in affect

```
self.effect()
```

  File "sendto_silhouette.py", line 930, in effect

```
pressure=self.options.pressure, speed=self.options.speed)
```

  File "C:\Program Files (x86)\Inkscape\share\extensions\silhouette\Graphtec.py", line 295, in setup

```
s.home()
```

  File "C:\Program Files (x86)\Inkscape\share\extensions\silhouette\Graphtec.py", line 267, in home

```
s.write("TT\x03")
```

  File "C:\Program Files (x86)\Inkscape\share\extensions\silhouette\Graphtec.py", line 230, in write

```
raise ValueError('write %d bytes failed: r=%d' % (len(chunk), r))
```

ValueError: write 3 bytes failed: r=0

Then I tried again
 without removing the card and reinserting it. The cutter didn't move and I got the following error:

Traceback (most recent call last):

  File "sendto_silhouette.py", line 997, in <module>

```
e.affect()
```

  File "C:\Program Files (x86)\Inkscape\share\extensions\inkex.py", line 215, in affect

```
self.effect()
```

  File "sendto_silhouette.py", line 880, in effect

```
state = dev.status()    # hint at loading paper, if not ready.
```

  File "C:\Program Files (x86)\Inkscape\share\extensions\silhouette\Graphtec.py", line 252, in status

```
resp = s.read(timeout=5000)
```

  File "C:\Program Files (x86)\Inkscape\share\extensions\silhouette\Graphtec.py", line 239, in read

```
data = s.dev.read(endpoint, size, timeout=timeout, interface=0) 
```

  File "C:\Program Files (x86)\Inkscape\python\lib\site-packages\usb\core.py", line 654, in read

```
self.__get_timeout(timeout)
```

  File "C:\Program Files (x86)\Inkscape\python\lib\site-packages\usb\backend\libusb01.py", line 483, in bulk_read

```
timeout)
```

  File "C:\Program Files (x86)\Inkscape\python\lib\site-packages\usb\backend\libusb01.py", line 568, in __read

```
timeout
```

  File "C:\Program Files (x86)\Inkscape\python\lib\site-packages\usb\backend\libusb01.py", line 384, in _check

```
raise USBError(errmsg, ret)
```

usb.core.USBError: [Errno None] libusb0-dll:err [_usb_reap_async] timeout error

Finally, I removed the card and reinserted it and the cutter didn't move but I got the following error:

Traceback (most recent call last):

  File "sendto_silhouette.py", line 997, in <module>

```
e.affect()
```

  File "C:\Program Files (x86)\Inkscape\share\extensions\inkex.py", line 215, in affect

```
self.effect()
```

  File "sendto_silhouette.py", line 930, in effect

```
pressure=self.options.pressure, speed=self.options.speed)
```

  File "C:\Program Files (x86)\Inkscape\share\extensions\silhouette\Graphtec.py", line 354, in setup

```
s.write("TB71\x03")
```

  File "C:\Program Files (x86)\Inkscape\share\extensions\silhouette\Graphtec.py", line 230, in write

```
raise ValueError('write %d bytes failed: r=%d' % (len(chunk), r))
```

ValueError: write 5 bytes failed: r=0

That's a lot in one go, but I hope it helps!

cheers

Jason

**Comment by jnweiger** [comment]
I never tried using an sd card. I am not sure I understand what you did: You saved your drawing from inkscape to sdcard and managed to cut it then?

Libusb not listing any devices is bad. That looks like we miss another piece of the puzzle. 

Cheers, jw

JLiver notifications@github.com schrieb:

> Just to add an extra bit of information, I read the instructions on
> libusb, and ran the inf-wizard program which created an inf file. 
> 
> I then tried send some cuts to Silhouette, and it worked. 
> 
> When I sent it a second time, I got the following error:
> 
> Traceback (most recent call last):
>  File "sendto_silhouette.py", line 997, in <module>
>    e.affect()
> File "C:\Program Files (x86)\Inkscape\share\extensions\inkex.py", line
> 215, in affect
>    self.effect()
>  File "sendto_silhouette.py", line 930, in effect
>    pressure=self.options.pressure, speed=self.options.speed)
> File "C:\Program Files
> (x86)\Inkscape\share\extensions\silhouette\Graphtec.py", line 294, in
> setup
>    s.initialize()
> File "C:\Program Files
> (x86)\Inkscape\share\extensions\silhouette\Graphtec.py", line 263, in
> initialize
>    s.write("\x1b\x04")
> File "C:\Program Files
> (x86)\Inkscape\share\extensions\silhouette\Graphtec.py", line 230, in
> write
>    raise ValueError('write %d bytes failed: r=%d' % (len(chunk), r))
> ValueError: write 2 bytes failed: r=0
> 
> I then removed the card and reinserted it into the cutter. I stopped
> and started Inkscape.
> 
> The cutter then ran the card backwards and forwards a couple of times.
> It then cut the shapes that I drew, and finally gave the following
> error:
> 
> Traceback (most recent call last):
> 
>  File "sendto_silhouette.py", line 997, in <module>
> 
>    e.affect()
> 
> File "C:\Program Files (x86)\Inkscape\share\extensions\inkex.py", line
> 215, in affect
> 
>    self.effect()
> 
>  File "sendto_silhouette.py", line 961, in effect
> 
>    state = dev.status()
> 
> File "C:\Program Files
> (x86)\Inkscape\share\extensions\silhouette\Graphtec.py", line 251, in
> status
> 
>    s.write("\x1b\x05")
> 
> File "C:\Program Files
> (x86)\Inkscape\share\extensions\silhouette\Graphtec.py", line 230, in
> write
> 
>    raise ValueError('write %d bytes failed: r=%d' % (len(chunk), r))
> 
> ValueError: write 2 bytes failed: r=0
> 
> Then I tried again
> without removing the card and reinserting it. The cutter didn't move
> and I got the following error:
> 
> Traceback (most recent call last):
> 
>  File "sendto_silhouette.py", line 997, in <module>
> 
>    e.affect()
> 
> File "C:\Program Files (x86)\Inkscape\share\extensions\inkex.py", line
> 215, in affect
> 
>    self.effect()
> 
>  File "sendto_silhouette.py", line 930, in effect
> 
>    pressure=self.options.pressure, speed=self.options.speed)
> 
> File "C:\Program Files
> (x86)\Inkscape\share\extensions\silhouette\Graphtec.py", line 295, in
> setup
> 
>    s.home()
> 
> File "C:\Program Files
> (x86)\Inkscape\share\extensions\silhouette\Graphtec.py", line 267, in
> home
> 
>    s.write("TT\x03")
> 
> File "C:\Program Files
> (x86)\Inkscape\share\extensions\silhouette\Graphtec.py", line 230, in
> write
> 
>    raise ValueError('write %d bytes failed: r=%d' % (len(chunk), r))
> 
> ValueError: write 3 bytes failed: r=0
> 
> Then I tried again
> without removing the card and reinserting it. The cutter didn't move
> and I got the following error:
> 
> Traceback (most recent call last):
> 
>  File "sendto_silhouette.py", line 997, in <module>
> 
>    e.affect()
> 
> File "C:\Program Files (x86)\Inkscape\share\extensions\inkex.py", line
> 215, in affect
> 
>    self.effect()
> 
>  File "sendto_silhouette.py", line 880, in effect
> 
>    state = dev.status()    # hint at loading paper, if not ready.
> 
> File "C:\Program Files
> (x86)\Inkscape\share\extensions\silhouette\Graphtec.py", line 252, in
> status
> 
>    resp = s.read(timeout=5000)
> 
> File "C:\Program Files
> (x86)\Inkscape\share\extensions\silhouette\Graphtec.py", line 239, in
> read
> 
>    data = s.dev.read(endpoint, size, timeout=timeout, interface=0) 
> 
> File "C:\Program Files
> (x86)\Inkscape\python\lib\site-packages\usb\core.py", line 654, in read
> 
>    self.__get_timeout(timeout)
> 
> File "C:\Program Files
> (x86)\Inkscape\python\lib\site-packages\usb\backend\libusb01.py", line
> 483, in bulk_read
> 
>    timeout)
> 
> File "C:\Program Files
> (x86)\Inkscape\python\lib\site-packages\usb\backend\libusb01.py", line
> 568, in __read
> 
>    timeout
> 
> File "C:\Program Files
> (x86)\Inkscape\python\lib\site-packages\usb\backend\libusb01.py", line
> 384, in _check
> 
>    raise USBError(errmsg, ret)
> 
> usb.core.USBError: [Errno None] libusb0-dll:err [_usb_reap_async]
> timeout error
> 
> Finally, I removed the card and reinserted it and the cutter didn't
> move but I got the following error:
> 
> Traceback (most recent call last):
> 
>  File "sendto_silhouette.py", line 997, in <module>
> 
>    e.affect()
> 
> File "C:\Program Files (x86)\Inkscape\share\extensions\inkex.py", line
> 215, in affect
> 
>    self.effect()
> 
>  File "sendto_silhouette.py", line 930, in effect
> 
>    pressure=self.options.pressure, speed=self.options.speed)
> 
> File "C:\Program Files
> (x86)\Inkscape\share\extensions\silhouette\Graphtec.py", line 354, in
> setup
> 
>    s.write("TB71\x03")
> 
> File "C:\Program Files
> (x86)\Inkscape\share\extensions\silhouette\Graphtec.py", line 230, in
> write
> 
>    raise ValueError('write %d bytes failed: r=%d' % (len(chunk), r))
> 
> ValueError: write 5 bytes failed: r=0
> 
> That's a lot in one go, but I hope it helps!
> 
> cheers
> 
> Jason
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jnweiger/inkscape-silhouette/issues/2#issuecomment-33279126

## 

Diese Nachricht wurde nicht von einem iPhone gesendet. K-9 mail

**Comment by JLiver** [comment]
Hi Jurgen

Libsub didn't list a device in my first post, then I ran the inf-wizard program and the software found the device and was able to cut, which is the series of tests in my second post.

In the second post, when I said card, I meant the thick paper type of card that I was cutting into, not SD card. :)

**Comment by JLiver** [comment]
Sorry, pressed the wrong button.

**Comment by jnweiger** [comment]
Hey, congratulations! You are the first person to cut stuff with inkscape under windows!

I try reading about this inf-wizard. This topic is very unclear to me. Possibly as I am not a windows native.
Can you please include a step by step procedure in the documentation?

Ah, okay, so it was cardboard, not sd-cards.  I guess it is very hard to cut a pattern into an sd-card :-))

**Comment by JLiver** [comment]
Thankyou :)

I don't really know either. I think that the inf wizard sets up a configuration file that lib-usb then uses.

Anyway, rebooted and tried to cut today, and had the follow error:

Traceback (most recent call last):
  File "sendto_silhouette.py", line 997, in <module>
    e.affect()
  File "C:\Program Files (x86)\Inkscape\share\extensions\inkex.py", line 215, in affect
    self.effect()
  File "sendto_silhouette.py", line 949, in effect
    bboxonly=self.options.bboxonly)
  File "C:\Program Files (x86)\Inkscape\share\extensions\silhouette\Graphtec.py", line 449, in plot
    s.write("FM1\x03")          # // ?
  File "C:\Program Files (x86)\Inkscape\share\extensions\silhouette\Graphtec.py", line 230, in write
    raise ValueError('write %d bytes failed: r=%d' % (len(chunk), r))
ValueError: write 4 bytes failed: r=0

The cutter didn't work, sorry about that. :-

**Comment by JLiver** [comment]
Now, I've tried pressing the cut button again without closing your form, and the cutter worked on this second button press. At the end I had the following error even though everything looked ok:

Traceback (most recent call last):
  File "sendto_silhouette.py", line 997, in <module>
    e.affect()
  File "C:\Program Files (x86)\Inkscape\share\extensions\inkex.py", line 215, in affect
    self.effect()
  File "sendto_silhouette.py", line 949, in effect
    bboxonly=self.options.bboxonly)
  File "C:\Program Files (x86)\Inkscape\share\extensions\silhouette\Graphtec.py", line 525, in plot
    s.write(p)
  File "C:\Program Files (x86)\Inkscape\share\extensions\silhouette\Graphtec.py", line 233, in write
    raise ValueError('write all %d bytes failed: o=%d' % (len(string), o))
ValueError: write all 12153 bytes failed: o=12288

The cutter had managed to get about halfway through when the error happened.

**Comment by jnweiger** [comment]
I am adding some code to give it a retry, when a single write fails. 
Please check out commit#f4e3db4

**Comment by JLiver** [comment]
Hi Jurgen

Sorry for the delay, I've been away for a few days. I downloaded the zip file on the right of the project page and extracted the contents into my Inkscape's Python folder. Then I started Inkscape and tried to cut something. I didn't extract misc or examples folders in the zip file.

I had the following error message:

No Graphtec Silhouette devices found.
Check USB and Power.
Devices: (0408,2fb1) 

I tried with Silhouette Studio and was able to cut with that.

cheers

Jason

**Comment by jnweiger** [comment]
The Device IDs for your Silhouette Cameo would have been (0b4d,1121) 
It is not reported in the devices list, which means, libusb isn't seeing the device at all. 
Maybe you have to redo the inf-wizard magic again?

The (0408,2fb1) that you see is the webcam in your Dell XPS notebook :-)

**Comment by jnweiger** [comment]
Jason, are you still there? Please reopen, if you think I could help you some more.
