### ISSUE TITLE
SilhouetteCameo  ImportError

### ISSUE THREAD

**Issue by MaurinElectroTextile** [fablabnbg/inkscape-silhouette#27]
I'm runing Linux Xubuntu
I did the install as below

```
~/.config/inkscape/extensions/inkscape-silhouette/
~/.config/inkscape/extensions/sendto_silhouette.inx
~/.config/inkscape/extensions/sendto_silhouette.py
```

I added the udev rules 

```
  /etc/udev/rules.d/silhouette-udev.rules
  /usr/lib/udev/silhouette-udev-notify.sh
```

I get this ERROR

```
 File "sendto_silhouette.py", line 120, in <module>
 from silhouette.Graphtec import SilhouetteCameo
 ImportError: No module named silhouette.Graphtec
```

**Comment by EtherGraf** [comment]
In my installation there is an directory
~/.config/inkscape/extensions/silhouette/ (without incscape!) containing Graphtec.py
I think you have missspelled the directory.

**Comment by MaurinElectroTextile** [comment]
Yes it is.
Merci ;-)

**Comment by Geekoid85** [comment]
Hi guys !
I think I have the same error as you but not seem to have the same directory problem : 
![image](https://user-images.githubusercontent.com/38323963/50372620-0a902280-05d2-11e9-9721-08cbc28cef43.png)
![image](https://user-images.githubusercontent.com/38323963/50372622-1aa80200-05d2-11e9-834f-f3f1b2c84b36.png)
I'm on debian 9. I have put the .py and .inx in the inkscape root directory and also keep them in the silhouette folder (I have try to delete those who are in the silhouette directory and only keep those who are in the inkscape root directory, nothing's changed)

So... Merci pour votre aide !
