### ISSUE TITLE
Doesn't work on Debian Stretch

### ISSUE THREAD

**Issue by mattmon** [fablabnbg/inkscape-silhouette#28]
Files get installed to /usr/bin

I made a feeble attempt at getting it working by moving the extension into inkscape's path and adding the udev rules to my system, but still no go.

**Comment by SuzanneSoy** [comment]
@mattmon Do you mean that the extension does not show up in the <kbd>Extensions</kbd> → <kbd>Export</kbd> → <kbd>Send To Silhouette</kbd> menu? Or does it fail later? If it's the latter, is there any error message from the extension?

**Comment by mattmon** [comment]
All the files contained in the .deb archive are just dumped into /usr/bin.

The udev rules dont get installed to /etc/udev/rules.d and the extensions (.inx / .py) don't get installed to /usr/share/inkscape/extensions.

After manually placing the files and restarting udev, I can see the extension from within inkscape, but it doesn't work, producing no output.

That's as far as I got.

Would really like to use your software! Converting from SVG to DXF, then firing up a windows VM just to use Silhouette's crappy software is not ideal :)

**Comment by SuzanneSoy** [comment]
@mattmon I'm not the developer of this extension, but I asked these questions as I thought their answers would be useful to help debug the problem.

FWIW, I installed the extension using (roughly) the steps in the README for Ubuntu 14.04 on another distribution (nix-os): install the python-usb library via the package manager, download the .zip from GitHub, and put the files `sendto_silhouette.inx`, `sendto_silhouette.py` and the `silhouette` folder in `/root/.config/inkscape/extensions/`, and run Inkscape as root with `sudo`. I didn't need to setup any `udev` rules that way.

I didn't see a pre-packaged `.deb` anywhere, though, are you talking about `.deb` for `python-usb`, or is there a version of `inkscape-silhouette` packaged as a `.deb` somewhere? Do you have a link to that specific `.deb` file? It might be worth trying out a manual installation as I did. I agree the `DXF` conversion is a pain :) .

**Comment by EtherGraf** [comment]
Just an idea to check:

You have installed libusb-1.0?

**Comment by EtherGraf** [comment]
> After manually placing the files and restarting udev, I can see the extension from within inkscape, but it doesn't work, producing no output.

Does this mean, you see the menu entry or does this mean, the extension 
opens and you see the window with the settings?

**Comment by mattmon** [comment]
I used the deb file posted [in the wiki](https://software.opensuse.org/download.html?project=home%3Ajnweiger%3Afablab&package=inkscape-silhouette),

Yes, libusb is installed - the deb enforces this with it's dependency upon python-usb, though the version packaged with debian is 0.1.

Yes, I can see the extension in the menu and manipulate it's settings, but they seem to have no effect.

Would rather not run inkscape as root, it should be entirely possible to make this work without it!

**Comment by EtherGraf** [comment]
> Yes, libusb is installed - the deb enforces this with it's dependency upon python-usb, though the version packaged with debian is 0.1.

I remember weakly there was some problems with libusb-0.1
I dont know details anymore, but on ubuntu14.04 I had to install 
libusb-1.0 to get it working.

I had to do this aside the apt package manager with
'pip install libusb1'
or similar.

> Yes, I can see the extension in the menu and manipulate it's settings, but they seem to have no effect.
> 
> Would rather not run inkscape as root, it should be entirely possible to make this work without it!

After setup the udev rules correctly it _IS_ possible to run without 
root privileges. This was only meant as a first test. In my environment 
it runs with user rights.

For further tests you can run the script even without inkscape. Just run
'python sendto_silhouette.py xyz.svg'
or
'python arrow-test.py'
from commandline. This will plot some small arrows if running sucessfully.

Then you should see some error messages which will help.

**Comment by jnweiger** [comment]
@mattmon Are you installing the deb package from https://github.com/fablabnbg/inkscape-silhouette/releases ? 
There I have a dependency on libusb >= 1.0.0 
and the files should properly go into the right places. 

We probably have to drop the hard libusb dependency, as even the newest systems fail here and ship a prehistoric 0.1 version only ... The code won't run with anything less than 1.0.0 so this remains a documentation item, and as @EtherGraf already suggested, pip install is probably the best workaround for this.

**Comment by mattmon** [comment]
@jnweiger Everything works after installing the release deb and libusb-1.0-0  :-)

Thanks so much for creating this!
Cutting directly from Inkscape is SO much better than Silhouette's cripple-ware.
Both quality and speed of cuts are greatly improved!

Best of all, I don't have to pay money-grubbing Silhouette for the SVG support that their machine should have come out of the box with! 

FWIW, all current Debian releases have an available libusb-1.0-0 package - you might consider adding it as a dependency because python-usb pulls in the older libusb-0.1-4 package.

**Comment by probonopd** [comment]
Also, might want to check out the [AppImage](https://github.com/fablabnbg/inkscape-silhouette/issues/30) - comes with libusb bundled and doesn't need to be installed.

**Comment by jnweiger** [comment]
@mattmon :+1: :+1: :+1: 
I  think I should remove the copy in https://software.opensuse.org -- at least as long as I forget to keep them in sync...  Done.
