### ISSUE TITLE
silhouette.Graphtec

### ISSUE THREAD

**Issue by ncp1113** [fablabnbg/inkscape-silhouette#3]
I am attempting to use this on Mac OS X Mavericks but even after putting through all of the recommended dependencies I get "Import error: No module named silhouette.Graphtec" from line 89.

**Comment by jnweiger** [comment]
Where did you install the files to?
My notes say, it should go into /Applications/Inkscape.app/Contents/Resources/extensions/
is that correct?
Did you install all three: the two sendto_silhouette.\* files and the silhouette subfolder?

If so: I've added an attempt to include the directory of the running python script in the python search path. Maybe that helps. Please check out commit e56252f, version 1.9b or later.

**Comment by jnweiger** [comment]
inactive. closing.
