### ISSUE TITLE
Detect object fills

### ISSUE THREAD

**Issue by hellocatfood** [fablabnbg/inkscape-silhouette#39]
I'm using my Silhouette machine to do lots of drawings using a pen holder. In addition to drawing the outlines of a shape one thing I want to do is use the plotter to colour/fill them in. Is there a way to use this extension to detect fills in objects and fill them in? Or should I find a way using Inkscape to first convert a fill to a stroke?

**Comment by hellocatfood** [comment]
With thanks to the Inkscape forum I have discovered the EggBot inkscape extension that can fill an object with lines. https://github.com/evil-mad/EggBot

Once the extension is installed it can be found in:

Extensions > EggBot > Hatch Fill

**Comment by devingfx** [comment]
For people arriving here in 2025: there is now an extract of EggBot's Hatch fill to be a [standalone extension](https://inkscape.org/~Moini/%E2%98%85hatch-fill+1) ;)
