### ISSUE TITLE
'Device' object has no attribute 'bus'

### ISSUE THREAD

**Issue by mscalone** [fablabnbg/inkscape-silhouette#4]
Hi, 
I used to use 'robocut' with  Silhouette Portrait (with a little patch to rotate 180deg the page) and I'm really glad to see you developed a inkscape plugin. I'm testing right now in Ubuntu 14.04, pyusb-1.0.0b1 with my Silhouette Portrait an 
inkscape 0.48 show the following error:

'Device' object has no attribute 'bus'

any idea?

thanks and great job.
Marco

PS. Could you teld me What IDE/editor do you use to develop in python and how do you debug the inkspace plugin? thanks. If I have some free time I would like to contribute to this project.

**Comment by jnweiger** [comment]
No IDE used here. I have two ways to debug plugins. One is to generate a popup via inkex.debug("hello") the other is console output.
The first is extremly annoying, if you have many of them. The latter requires you to start inkscape from a terminal, so that you can see the output at all. You'll find many statments like these in the code:

print >>self.tty, "Hello"

This how I debug. Not nice, but works for me. 

Alas, dev.bus is only used for a debug print. I'll try to make failures harmless here.

**Comment by jnweiger** [comment]
Please retry with commit 2933cf8

**Comment by mscalone** [comment]
Excellent! last commit worked perfectly! 

After that I had permission errors, but I quickly realize that I need to add access to the device: 
- copy silhouette-udev.rules to /etc/udev/udev.d/
- copy silhouette-udev-notify.sh to /usr/lib/udev/
- restart udev: sudo udevadm trigger

Maybe it's useful to add this steps to the readme. One thing it's wrong in the readme its that the 'Misfeatures' actually DO work (at least for pen plot on Silhouette Portrait):
- polygons, and boxes are plotted closed
- and only plots selected objects or visible layers

Great, Job! thank you very much 

PS. I wander if you plan to add in the feature the 'registration marks calibration' feature robocut has

**Comment by jnweiger** [comment]
The readme mentions these as misfeatures of one version of robocut that I tested. Do I get it right, that these are fixed in robocut meanwhile?

**Comment by jnweiger** [comment]
I'd love to have the registration marks calibration feature in the inkscape plugin too.
Haven't looked into it. If it needs a more interactive user interface, then we run into trouble.

**Comment by jnweiger** [comment]
except for the added feature request, this issue is solved.
