### ISSUE TITLE
error keeps returning

### ISSUE THREAD

**Issue by mountaineermaniac** [fablabnbg/inkscape-silhouette#40]
Hi  hopefully I can get some help here and get this issue resolved. Trying to get my wife onboard with linux. She has a Silhouette Cameo and using inkscape 0.92.1 and Ubuntu 16.04, I installed the extension "export/send to silhouette" from [.]http://www.instructables.com/id/Inkscape-Silhouette-UbuntuRPi/(url) Typically the first time opening the app it will send to the cameo, there after, it will no longer work, continually getting the error message:
****Inkscape has received additional data from the script executed. 
The script did not return an error, but this may indicate the results will not be as expected****

`Traceback (most recent call last):
  File "sendto_silhouette.py", line 1109, in <module>
    e.affect()
  File "/usr/share/inkscape/extensions/inkex.py", line 283, in affect
    self.effect()
  File "sendto_silhouette.py", line 961, in effect
    state = dev.status()    # hint at loading paper, if not ready.
  File "/usr/share/inkscape/extensions/silhouette/Graphtec.py", line 393, in status
    print("usb.core.USBError:", e, file=self.log)
NameError: global name 'self' is not defined`

Looking for any help to get this fixed.  Thank You

**Comment by EtherGraf** [comment]
I cannot tell you the exact reason, but there seems to be some problems 
with the USB communication. Maybe a timeout, or starting without media.

At least there is an error in the error handling code, which leads to 
the program abort.

Change the line in Graphtec.py

       print("usb.core.USBError:", e, file=self.log)
to
       print("usb.core.USBError:", e, file=s.log)

and tell the result.

Regards,
Johann

Am 06.04.2017 um 16:15 schrieb mountaineermaniac:
> Hi  hopefully I can get some help here and get this issue resolved. Trying to get my wife onboard with linux. She has a Silhouette Cameo and using inkscape 0.92.1 and Ubuntu 16.04, I installed the extension "export/send to silhouette" from [.]http://www.instructables.com/id/Inkscape-Silhouette-UbuntuRPi/(url) Typically the first time opening the app it will send to the cameo, there after, it will no longer work, continually getting the error message:
> ****Inkscape has received additional data from the script executed.
> The script did not return an error, but this may indicate the results will not be as expected****
>
> `Traceback (most recent call last):
>   File "sendto_silhouette.py", line 1109, in <module>
>     e.affect()
>   File "/usr/share/inkscape/extensions/inkex.py", line 283, in affect
>     self.effect()
>   File "sendto_silhouette.py", line 961, in effect
>     state = dev.status()    # hint at loading paper, if not ready.
>   File "/usr/share/inkscape/extensions/silhouette/Graphtec.py", line 393, in status
>     print("usb.core.USBError:", e, file=self.log)
> NameError: global name 'self' is not defined`
>
> Looking for any help to get this fixed.  Thank You
>
>

**Comment by mountaineermaniac** [comment]
Appears to have worked after a few attempts at printing.  I also moved the connection to a more dedicated usb port on the front of the computer. Will spend more time with it and update as I get the time.  

Thanks for the help,
Don

**Comment by EtherGraf** [comment]
Just checked in this fix in the master branch.
Issue closed.
