### ISSUE TITLE
Does this plugin work for the silhouette curio?

### ISSUE THREAD

**Issue by grafnugi** [fablabnbg/inkscape-silhouette#46]
Trying to get this Curio operational, installed the extension fine but I'm not suru what to do next, do I install the Curio as a printer? If so , which driver do i use?

**Comment by EtherGraf** [comment]
No need to install a printer driver.
Start inkscape, open your file, select some or all paths to plot. 
Menu Extensions / Export / Send to Silhouette...

I have no idea if this extension works with a curio.

**Comment by jnweiger** [comment]
There was sone progress with curio support in https://github.com/fablabnbg/inkscape-silhouette/issues/36 but I am not sure if it worked in the end.

**Comment by t0b3** [comment]
@grafnugi did you succeed with Curio?
