### ISSUE TITLE
debian installation instructions: fetching release key: 404 error

### ISSUE THREAD

**Issue by AVHon** [fablabnbg/inkscape-silhouette#47]
Running the following line:
```wget http://download.opensuse.org/repositories/home:jnweiger:fablab/xUbuntu_14.10/Release.key -O - | sudo apt-key add -```
on Debian Jessie 8 fails. Specifically, wget 404's on the link. The proper version should be:
```wget https://download.opensuse.org/repositories/home:jnweiger:fablab/xUbuntu_14.10/Release.key -O - | sudo apt-key add -```

**Comment by EtherGraf** [comment]
Just tested it on my ubuntu. 
Both lines fails on ubuntu with 404. So I don't think the https protocol is the only reason.

**Comment by EtherGraf** [comment]
For me 
`http://download.opensuse.org/repositories/home:/jnweiger:/fablab/xUbuntu_14.04/Release.key`
is the correct path and works both with http and https.
Pay attention to the semicolons.

**Comment by jnweiger** [comment]
The README.md is a mess. Sorry for that.
Ive added references to github releases there but failed to remove the old references to the opensuse build service. The build project home:jnweiger:fablab no longer exists.
