### ISSUE TITLE
Support for 12" x 24" cutting mat

### ISSUE THREAD

**Issue by ChristianZi** [fablabnbg/inkscape-silhouette#51]
Hi, 

there's also a larger cutting mat (24" x 12"). I was not able to do anything in the lower part of the mat.
Are there plans to support this in future?

regards
Christian

**Comment by EtherGraf** [comment]
I am not aware of any hardcoded size limit.
I assume you have enlarged the page size of the document properly?

**Comment by dbajar** [comment]
See bc3f9478de8d51b16e1ac70ee72a13f0689cb63f

**Comment by solarkennedy** [comment]
Hmm. @dbajar where does the `TG2\x03` come from? Are there other magic strings for the other cutting mat sizes? (I would like an option for the Portrait standard mat)

**Comment by dbajar** [comment]
The TGx command is undocumented.  The command and its values were discovered by trying various options in the commercial software and observing with sniffer.  If I recall, "no mat", "12x12" and "24x12" were the only options available at the time (at least for Cameo3).

Are there more options available now?

**Comment by ConorIA** [comment]
@dbajar, the Portrait uses 8 x 12. Not sure if that matters when actually running this thing, since it looks like the portrait is supported.

**Comment by t0b3** [comment]
12"x24" mat support is in master branch now and works with inkscape 1.0.1
@ChristianZi @dbajar @solarkennedy @ConorIA you are welcome to try latest master and provide feedback or open new issues
