### ISSUE TITLE
Invalid response from plotter. (Silhouette Portrait)

### ISSUE THREAD

**Issue by tuxedo0801** [fablabnbg/inkscape-silhouette#54]
I'm using Debian Testing with Inkscape 0.92.2 and latest inkscape-silhouette release 1.19-1 and Silhouette Portrait.

When trying to do a very simple plot:

![bildschirmfoto vom 2017-11-30 08-38-29](https://user-images.githubusercontent.com/2862906/33419239-db716652-d5a9-11e7-8b94-1e74f7fed1ee.png)

with vinyl settings:

![bildschirmfoto vom 2017-11-30 08-39-20](https://user-images.githubusercontent.com/2862906/33419291-040527e8-d5aa-11e7-8885-32b50df3008c.png)
and additionally
+ "Wait til done"
+ "Optimize for cutting without mat"

I get this error message after the plotter makes a very short movement-noise (1/10 sec or so)

![bildschirmfoto vom 2017-11-30 08-35-42](https://user-images.githubusercontent.com/2862906/33419160-809e164e-d5a9-11e7-9dfe-31910eac5dd5.png)

I also sent to the dummy device, which produces this file:

[silhouette.dump.zip](https://github.com/fablabnbg/inkscape-silhouette/files/1516903/silhouette.dump.zip)

lsusb tells me:

```bash
Bus 001 Device 039: ID 0b4d:1123 Graphtec America, Inc. 
```

What can I do to fix this issue? Any hints?

**Comment by jnweiger** [comment]
The error happens after sending the TB71 command. We no longer do that.
You can pull an update from 
https://github.com/fablabnbg/inkscape-silhouette/blob/master/silhouette/Graphtec.py#L495

and the error will go away.

**Comment by northmeade** [comment]
I replaced the update from above but am now getting this

Traceback (most recent call last):
  File "sendto_silhouette.py", line 122, in <module>
    from silhouette.Graphtec import SilhouetteCameo
  File "/usr/share/inkscape/extensions/silhouette/Graphtec.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

can you help please.

**Comment by t0b3** [comment]
@tuxedo0801 you are welcome to try the latest changes in master and provide feedback or open new issues...
The code is expected to work with Inkscape 1.0.1 now.
