### ISSUE TITLE
Final stroke is not processed

### ISSUE THREAD

**Issue by myselfhimself** [fablabnbg/inkscape-silhouette#55]
Hello,
Per the current README version content:

> Stars, polygons, and boxes are plotted not closed, the final stroke is missing. (Must be me, no?)

I have managed to reproduce that issue on Ubuntu Linux 16.04, using the distribution's deb package, with Inkscape 0.91 and Silhouette Cameo 3.

Here is just a reminder issue, so that someone fixes that issue (it could be me in some weeks..).

Thanks :-)

**Comment by myselfhimself** [comment]
@lexelby is https://github.com/lexelby/inkscape-silhouette/commit/b24f0199f3ecd89d20947d288e5218c12bd7ea6d the fix for the current issue?

**Comment by jnweiger** [comment]
There are floating point comparisons for equal in the code. this is bad. Can you give an example svg, where the final stroke is missing? I have a slightly different implementation in https://github.com/jnweiger/inkscape-thunderlaser/blob/master/src/inksvg.py where I cannot find any such floating point comparisons.

I'd like to check if that code shows the same bug.

**Comment by myselfhimself** [comment]
Hello,
here is an example SVG, the right-side red edges are not cut.
[cardbox_71_x_210_x_36_mm.svg.txt](https://github.com/fablabnbg/inkscape-silhouette/files/1587668/cardbox_71_x_210_x_36_mm.svg.txt)

**Comment by myselfhimself** [comment]
Using lexelby's master branch containing the abovementioned commit does not solve.

**Comment by jnweiger** [comment]
Thanks for the example! inksvg.py seems to find all lines.

**Comment by myselfhimself** [comment]
OK sorry, for taking your time.
Here is another file with an open edge, that helps debugging better.
My Cameo 3 cuts everything through in one direction with the "Send to silhouette..." dialogue.
But, when using the Silhouette Multiple-Actions dialog, it cuts the paper, starting from the opposite side (though not flipping the drawing) (ie. from the bottom edge's opened angle righthand point), leftwards then well to the top, stopping a bit before the top righthand side corner, without cutting the segments shown in red in the attached SVG file.

My conclusion is that.. the regular tools works good, and I have an issue with @lexelby 's master branch that is all. So my issue maybe does not relate to his project, but to a fork of it..

![bottom_open_angle](https://user-images.githubusercontent.com/1265346/34366273-b5d58090-ea99-11e7-96b9-ace711d28817.png)
![normal](https://user-images.githubusercontent.com/1265346/34366274-b6006ab2-ea99-11e7-973c-6f356fc37a2c.png)
![multiaction](https://user-images.githubusercontent.com/1265346/34366275-b62f418e-ea99-11e7-83d8-91045b185baf.png)
[cardbox_71_x_210_x_36_mm_DEBUG .svg.txt](https://github.com/fablabnbg/inkscape-silhouette/files/1588008/cardbox_71_x_210_x_36_mm_DEBUG.svg.txt)

**Comment by lexelby** [comment]
> @lexelby is lexelby/inkscape-silhouette@b24f019 the fix for the current issue?

That commit solves a different problem: paths that were closed were not being treated as such, so if you set "repeats" to >1, the knife will be unnecessarily lifted between repeats.  I'm not sure about the problem here that's mentioned in the README.

**Comment by t0b3** [comment]
@myselfhimself @lexelby you are welcome to try the latest changes in master and provide feedback or open new issues...
The code is expected to work with Inkscape 1.0.1 now.
