### ISSUE TITLE
'bytearray' has no attribute 'tostring' (MacOSX, Cameo2)

### ISSUE THREAD

**Issue by ideogram** [fablabnbg/inkscape-silhouette#57]
When trying this repro on MacOSX, Inkscape v. 0.92 on a Cameo 2, the machine doesn't do anything and the script gives an additional 'message'.

On the same computer, with Ubuntu in a VB, it works.

![screen shot 2018-01-20 at 14 03 26](https://user-images.githubusercontent.com/4469494/35183729-38fb5e2c-fdeb-11e7-95d6-7c5382886373.png)

**Comment by lgrawet** [comment]
Hi, I fixed it in #59 !

**Comment by EtherGraf** [comment]
Closed, because fixed in #59.

**Comment by ideogram** [comment]
Thank you!

Maarten v/d Velde
