### ISSUE TITLE
Feature request: Autoblade support

### ISSUE THREAD

**Issue by AdrianAbraham** [fablabnbg/inkscape-silhouette#70]
Could you support setting Autoblade depth for the Cameo 3?

**Comment by dbajar** [comment]
See 7e86b7da6005f02995a5e6fd469579002f112ac8

**Comment by olegdizus** [comment]
Hi, @dbajar! Do you plan to add PR?

**Comment by swzCuroverse** [comment]
Any news on this?

**Comment by olegdizus** [comment]
Hi, @swzCuroverse! I can suggest to use my fork - https://github.com/olegdeezus/inkscape-silhouette
I merged some PRs with autoblade support and multiple line profiles. Fork is tested and pretty stable for me. Maybe it fit your needs.

**Comment by swzCuroverse** [comment]
Thanks! I will give it a shot.  Do you have doc on how to use multiple line or is it pretty self-explanatory?  I am guessing autoblade (height) is just another selection with pressure, speed, etc.

**Comment by olegdizus** [comment]
Auto-blade option is added to "Send to Silhouette" dialog below speed and pressure options. Also you should select "Auto-blade" tool in tool selector.

Like this:
![Screen Recording 2019-04-23 at 21 09 43](https://user-images.githubusercontent.com/3694749/56609077-f3f7e780-6614-11e9-8035-88d24afea028.gif)

For using multi-line you should copy silhouette_multi files to inscape extensions folder (`~/.config/inkscape/extensions` on mac and linux, and `C:\Program Files\Inkscape\share\extensions` on windows)

But, for me multi-line options works only on linux. Both on mac and windows script can't find xmltodict library (it is installed). Maybe I doing something wrong.
Mutli-line options dialog is pretty user-friendly itself.

**Comment by swzCuroverse** [comment]
Thank you.  I will try it out.  I only use Linux (Ubuntu - Xenial Xerus) and just got a Cameo 3 so I will test those.

**Comment by jnweiger** [comment]
I have merged the fork from @olegdeezus back into master. Hope nothing broke during merge! One tester reported that autoblade feature is working in my version 1.21

Thanks Oleg and all for this great feature!
