### ISSUE TITLE
trouble installing on MacOS 10.13.6

### ISSUE THREAD

**Issue by cpress0717** [fablabnbg/inkscape-silhouette#71]
I installed homebrew, then tried installing the extension, per the instructions. I received an error: Renllaws-MBP:~ psgraphics$ sudo ./install_osx.py
Password:
sudo: ./install_osx.py: command not found

Can someone help me please?

Forgive me, in advance, for possibly asking something that has already been answered. I have tried reading through and have either not found the information or not read it correctly. I just need someone to point me in the right direction.

**Comment by bbustin** [comment]
Hi,

I’m sorry that it is not working for you. Here are the steps I recommend to troubleshoot and hopefully resolve the issue. 

1. make sure you are in the right directory (you probably are, but just to double-check) type ls and press enter. Make sure that install_osx.py is there
2. it is possible that install_osx.py does not have the executable bit set. Type chmod u+x install_osx.py and press enter. Then try running sudo ./install_osx.py again.
3. If all of the above fail, try running sudo python install_osx.py. 

Please let us know if this works or not and which step fixed the issue for you if you do get it working. 

- Brian

**Comment by orangefult** [comment]
I know this is like a year late... but hopefully it helps someone: 
If you right click on the application in finder, then click "Show package contents" then navigate to "Contents/Resources/share/inkscape/extensions" you can then download the master zip file and copy over the files "sendto_silhouette.inx", "sendto_silhouette.py" and the folder "silhouette" into that extensions folder, relaunch Inkscape and the extension shows up.

I've yet to verify that it will drive the vinyl cutter by installing the plugin that way, but I'm going to test it tonight and will report back here.

Here's a handy gif or two showing what I did.
![inkscape-silhouette-install-gui](https://user-images.githubusercontent.com/2236632/67417950-1dbfa600-f587-11e9-8af6-3e22ef11fdbf.gif)
![inkscape-boom](https://user-images.githubusercontent.com/2236632/67418043-4e074480-f587-11e9-81ff-562df814da24.gif)

**Comment by t0b3** [comment]
@orangefult @bbustin @cpress0717 you are welcome to try latest master which is expected to work with inkscape 1.0.1 as well...
provide your feedback to see if it works for you as well
