### ISSUE TITLE
optimized order for rolls

### ISSUE THREAD

**Issue by dlarue** [fablabnbg/inkscape-silhouette#73]
I was cutting names in 2 columns down 4' of vinyl and the only way I could figure out how to do it was to select 6" of letters then cut, select the next 6" and cut, etc etc. Otherwise, it wants to cut one column all the way from 0 - 4' then go back to the top of the vinyl and start on the 2nd column.

The names were originally done in 2 rows and then rotated 90 degrees and the page resized to the object.

Otherwise, really great software.  KUbuntu 18.04.1 on a Silhouette Portrait 2

**Comment by dlarue** [comment]
In hindsight, What I should have done was to cut the names horizontally wrapping any long names over 2 lines. I had originally wanted to keep all the characters in each name on a single label so that's why I rotated the names 90 degrees.

**Comment by t0b3** [comment]
closed with #141
