### ISSUE TITLE
Plugin window doesn't fit my screen

### ISSUE THREAD

**Issue by Geekoid85** [fablabnbg/inkscape-silhouette#74]
![image](https://user-images.githubusercontent.com/38323963/48659972-43305f80-ea5a-11e8-9cb7-e83daf470fed.png)
As you can see it's pretty bizarre. I can't resize it in heigh, and it won't fit even if I hide the xfce top toolbar.
Such a problem, I can't confirm my setting to send the job !

I hope it's easy to solved, I'm not enough skilled at python to fix that my self :/
Otherwise, a really nice job, thank you to all people who help making this silhouette studio alternative.

**Comment by EtherGraf** [comment]
This problem is already solved with pull request #68 by neocogent.
I have tested this patch already the last days, but found no time to merge it to master. 
I will do it now.

**Comment by Geekoid85** [comment]
Thanks a lot !

**Comment by Geekoid85** [comment]
![image](https://user-images.githubusercontent.com/38323963/50371930-85524100-05c4-11e9-9b4b-fef2ebe87de7.png)
This fix work perfectly :+1:
