### ISSUE TITLE
Scaling is off

### ISSUE THREAD

**Issue by bstabens** [fablabnbg/inkscape-silhouette#75]
I changed the document resolution to mm, but the scaling is totally off. It's about a fourth of the intended size... Also, it seems it's upside down. And I'm honestly totally puzzled by the whole scaling going on in document settings. Anybody here to give me a helping hand?

Thanks,
bstabens

**Comment by sxwid** [comment]
Hi, I had the same issue using Version 1.19 on a Cameo3. I used the current master and (most of) my offset issues are gone... Maybe that helps too?

**Comment by t0b3** [comment]
@bstabens you are welcome to try latest code in master and provide feedback on the recently introduced changes for introducing compatibility with inkscape 1.0...
