### ISSUE TITLE
Cameo 3 Tool: Pen, or Cut always uses Cutter

### ISSUE THREAD

**Issue by arolt** [fablabnbg/inkscape-silhouette#76]
I have a Cameo 3 on Elementary OS Juno (based on Ubuntu 18.04 LTS) and this plugin is working well with Inkscape, however, it doesn't seem to matter whether I choose Cut or Pen when sending a job. The device always uses the cutter.  Is this a known issue, or have I done something wrong?  I didn't seem to read this anywhere if this is the case.
Totally new to Inkscape and these types of machines (as well as github - I'm not a dev).
Thanks for the great work!

**Comment by EtherGraf** [comment]
I don't own a cameo 3, so I can't give precise informations. 
But I know, that cameo 3 is a relatively new device with ongoing work. I expect, that tool selection is not functional yet.

The existing combo box for selecting Pen or Cut only modifies the path slightly on corners to compensate the blade offset movements. It does not select another tool.

**Comment by KarenSte** [comment]
I have also a Cameo 3.
This device has a twin holder (see photo). Therefore you can cut and draw in one step. In Silhouette Studio you can select which line should be done by which tool.

It would be great if this would be possible with this plugin as well.

If you need any further details, just ask :)

![img_20190122_212803](https://user-images.githubusercontent.com/37994726/51563595-2ca8e900-1e8d-11e9-92ec-ec9982ce9c37.jpg)

**Comment by t0b3** [comment]
@arolt @KarenSte since ad55657f8696a893abca82948ce51e2862511d04 there is an option to select the **left** or **right** toolholder - not to confuse with selecting the tool itself **pen** or **cut** 
you are welcome to try the latest master branch and provide your feedback or open new issues...
