### ISSUE TITLE
zones in the portait dont cut using printing marks (margins)

### ISSUE THREAD

**Issue by jabiertxof** [fablabnbg/inkscape-silhouette#77]
Hi. First of all thanks for this great pieze of software.

In the attached file I have a problem with inkscape 0.92.4 in Debian Buster.
In the file attaches, the red zones dont be cut by my Shilluette portait. non red cut well using the printing marks.

Thanks in advance for get into,

[a4.zip](https://github.com/fablabnbg/inkscape-silhouette/files/2796658/a4.zip)

**Comment by EtherGraf** [comment]
This is known behaviour.

Cutting cannot take place outside of the registration marks with the current software. All cuts outside this area will be ommited. Maybe it is possible for the device, but the extension does not support it yet.

Another known small bug is that each line starting or ending in the invalid outer area will be dropped completely instead of cutting it at least to border. This is exactly what you have seen.

You have two options:
1. Rearange the cuts into the area inside the cutting marks. 
2. If not possible, try to shift the registration marks and adjust the according settings in the parameter page

**Comment by EtherGraf** [comment]
If you are a python developer and want try to fix it, i can give you a few starting hints.

**Comment by jabiertxof** [comment]
Hi @EtherGraf sorry for the late reply, 

I'm a active Inkscape dev, I could develop also we need to move the extension to wortk on Inkscape 1.0.

The main problem is I'm very busy doing my real live and Inkscape development, and maybe you or your organization could do this with less time and effort (and sure better) 

I send you my profile in gitlab to show is not only take out work from me but doing better handle man power for our common goal, improve inkscape and freedom people.

https://gitlab.com/users/jabiertxof/activity

With regards, Jabier.

**Comment by EtherGraf** [comment]
Hi Jabier, 

nice to get to know you. I do the developing for this project in my limited spare time. There is no company behind this. All contributions are driven by my personal needs. I am a ubuntu linux user and only a relatively active co developer, not the maintainer. 

I am willing to support the conversion to inkscape 1.0. I have not known up to now about this ongoing inkscape development. From my short glance to it, there should be no need for really big modifications. Conversion to python3 has undertaken first steps, but was not yet needed.  

Regards

**Comment by jabiertxof** [comment]
Thanks @EtherGraf I thing i can take some time. Thanks fot this cool piece of code!

**Comment by jabiertxof** [comment]
It also happends in original software from Shillutte so close the issue.

As workarround you can use a Pixscan board to allow full page printing.
 
I use a A4 printed with Shillutte Portait machine, but the rectangle is 19mm instead 21 so I align the right side print to the start of 3 little blackboxes., leaving 2mm at left little boxes.
Attached a file that can help. Just select page and with document properties switch from A4 to Pixscan Size to print or cut.

[pixscan.base.portait.zip](https://github.com/fablabnbg/inkscape-silhouette/files/3657354/pixscan.base.portait.zip)

thanks @EtherGraf  for get into!!!
