### ISSUE TITLE
How to insert registration marks into the document?

### ISSUE THREAD

**Issue by probonopd** [fablabnbg/inkscape-silhouette#79]
I see that there are files like `registration-marks-cameo-silhouette-a4-maxi.svg` but I am missing a GUI button "Insert registration marks into document". Does this feature exist? If not, could you please consider adding such a button, maybe next to "The document has registration marks"? Thanks.

**Comment by EtherGraf** [comment]
Such a button doesn't exist not yet.

But it shouldn't be to complicated to copy the markings from the template or to redraw it by self.
There are no special properties on the markings, draw just the square and the four lines on an appropriate place and set the according parameters.

You can draw the markings in scribus also, if it matches your workflow better.

**Comment by probonopd** [comment]
I see. Thank you. 

It started working for me when I used the `master` branch rather than the 1.19 release which seems to be quite a bit outdated by now.

Apparently it is sufficient to draw a black rectangle around the whole page, and a 1cm x 1cm black square in the upper right hand corner of that rectangle.

![](https://user-images.githubusercontent.com/2480569/51802939-f8e01180-2246-11e9-8b3b-5457efdeef94.png)

When I do this in Scribus, then it seems to get recognized properly. Sometimes I had to play a bit with the "Position of the regmark" settings in the plugin. It seems the tolerance there is a bit on the low side.

**Comment by miLORD1337** [comment]
I know it's old(ish), but I created an extension for creating silhouette registration marks. 
https://github.com/miLORD1337/silhouette-regmarks

Give it try if you like! Any feedback is greatly appreciated.

@t0b3 Should we add this to the hints for using registration marks, once it's confirmed running?

**Comment by t0b3** [comment]
it could help for sure to mention it. go for, once you can confirm it works...

**Comment by mofosyne** [comment]
Credits to @miLORD1337 for his work which is now merged in
