### ISSUE TITLE
no module name usb 1

### ISSUE THREAD

**Issue by ARKopp** [fablabnbg/inkscape-silhouette#81]
I got it it installed on a Mac 10.13.6 

the machine is connected with the usb and usb.core.find() gives me thins

<DEVICE ID 0b4d:112b on Bus 020 Address 007>

and usb.version_info[0] gives me 1

I get this error when I run the plugin in inkscape .. 

thanks for any help

<img width="477" alt="Screenshot 2019-03-25 21 59 57" src="https://user-images.githubusercontent.com/4289157/54954038-fb5e9f00-4f49-11e9-81c6-7bcd7407f58b.png">

**Comment by jnweiger** [comment]
Did you do the install with https://github.com/fablabnbg/inkscape-silhouette/blob/master/install_osx.py
?

**Comment by ARKopp** [comment]
Yes

Jürgen Weigert <notifications@github.com> schrieb am Di., 26. März 2019,
12:21 nachm.:

**Comment by jnweiger** [comment]
@bbustin Do you think it is an error to import usb1 there?

**Comment by jnweiger** [comment]
amongst others, `python ./install_osx.py` prints
```
Installed /Library/Python/2.7/site-packages/pyusb-1.0.2-py2.7.egg
Processing dependencies for pyusb
Finished processing dependencies for pyusb
Searching for libusb1
Reading https://pypi.python.org/simple/libusb1/
Best match: libusb1 1.7
Downloading https://files.pythonhosted.org/packages/9c/51/25f5218d9e21bac3e36bb7167d7d9dfe899cd48bebfe60a54cd39c5db585/libusb1-1.7.tar.gz#sha256=9d4f66d2ed699986b06bc3082cd262101cb26af7a76a34bd15b7eb56cba37e0f
Processing libusb1-1.7.tar.gz
Writing /tmp/easy_install-TinQns/libusb1-1.7/setup.cfg
Running libusb1-1.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-TinQns/libusb1-1.7/egg-dist-tmp-mKGAI1
warning: no files found matching 'testUSB1.py'
zip_safe flag not set; analyzing archive contents...
Copying libusb1-1.7-py2.7.egg to /Library/Python/2.7/site-packages
Adding libusb1 1.7 to easy-install.pth file

Installed /Library/Python/2.7/site-packages/libusb1-1.7-py2.7.egg
Processing dependencies for libusb1
Finished processing dependencies for libusb1
INFO: installing extension
INFO: making sure libusb is installed
ERROR: pyusb is not installed. Install script usually fails here on first attempt. Running it again should allow installation to complete.
```

Running it again prints 
```
Using /Library/Python/2.7/site-packages/pyusb-1.0.2-py2.7.egg
Processing dependencies for pyusb
Finished processing dependencies for pyusb
Searching for libusb1
Best match: libusb1 1.7
Processing libusb1-1.7-py2.7.egg
libusb1 1.7 is already the active version in easy-install.pth

Using /Library/Python/2.7/site-packages/libusb1-1.7-py2.7.egg
Processing dependencies for libusb1
Finished processing dependencies for libusb1
```

**Comment by jnweiger** [comment]
Afterwards, I can happily test successful installation with
```
$ python
Python 2.7.10 (default, Aug 17 2018, 17:41:52) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import usb1, usb.core
>>>
```

I cannot test with a physical silhouette cameo, I have are ca. 20km between mac and device.
@ARKopp do you get different messages, when you do what I did?

**Comment by ARKopp** [comment]
I got the same for this ... 

```
Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct  6 2017, 12:04:38) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import usb1, usb.core
>>> 

```

**Comment by ARKopp** [comment]
postitman:~ andy$ python
""Python 3.6.3 |Anaconda custom (64-bit)| (default, Oct  6 2017, 12:04:38) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import usb1, usb.core
>>> 
"""

**Comment by ARKopp** [comment]
```

$ sudo python ./install_osx.py
INFO: inkscape_silhouette install starting
INFO: installing inkscape_silhouette prerequisites
Searching for lxml
Best match: lxml 4.1.0
Adding lxml 4.1.0 to easy-install.pth file

Using /Users/andy/anaconda3/lib/python3.6/site-packages
Processing dependencies for lxml
Finished processing dependencies for lxml
Searching for pyusb
Best match: pyusb 1.0.2
Processing pyusb-1.0.2-py3.6.egg
pyusb 1.0.2 is already the active version in easy-install.pth

Using /Users/andy/anaconda3/lib/python3.6/site-packages/pyusb-1.0.2-py3.6.egg
Processing dependencies for pyusb
Finished processing dependencies for pyusb
Searching for libusb1
Best match: libusb1 1.7



Processing libusb1-1.7-py3.6.egg
libusb1 1.7 is already the active version in easy-install.pth

Using /Users/andy/anaconda3/lib/python3.6/site-packages/libusb1-1.7-py3.6.egg
Processing dependencies for libusb1
Finished processing dependencies for libusb1
INFO: installing extension
INFO: directory already exists '/Users/andy/.config/inkscape/extensions/silhouette'. Removing it and recreating it.
INFO: making sure libusb is installed
INFO: inkscape_silhouette extension install ended

```

**Comment by alt2014** [comment]
Hi, I had the same problem. It turns out that Inkscape was pointing to the default osx Python, but because I was using anaconda to manage my python environment, it was not registering that these packages existed. To fix this, I just altered "PATH_PYTHON" in Inkscape.app/Contents/Resources/bin/inkscape to point to the correct python. To figure out the correct path, just type "which python" in terminal.

**Comment by ARKopp** [comment]
great i am trying it out at the moment ...

**Comment by ARKopp** [comment]
<img width="652" alt="Screenshot 2019-04-05 10 05 21" src="https://user-images.githubusercontent.com/4289157/55613200-6437e980-578a-11e9-91d7-4257916779d6.png">

**Comment by jnweiger** [comment]
@ARKopp The error message is scrolled out of view in the screenshot. Can you please retry and make the tiny popup window a bit larger, so that we can see what comes after 

    from silhouette.Graphtec import SilhouetteCameo

**Comment by ARKopp** [comment]
that is the rest ...


Traceback (most recent call last):
  File "sendto_silhouette.py", line 124, in <module>
    from silhouette.Graphtec import SilhouetteCameo
  File "/Users/andy/.config/inkscape/extensions/silhouette/Graphtec.py", line 35, in <module>
    import usb1, usb.core
ImportError: No module named usb1

**Comment by mml1** [comment]
I had this issue too. I fixed it by adding a python-interpreter to the preferences file, which I found at /Users/mari/.config/inkscape. The documentation states to use `python-interpreter="/usr/bin/python2.7"`, but I used the location I found from doing `which python` and since my default is set to Python2 the path worked fine. You could use `python-interpreter="/usr/bin/python2.7"`, but you may need to install additional packages.

On a related note, it seems like Inkscape only works with Python2.

http://wiki.inkscape.org/wiki/index.php/Extension_Interpreters#Selecting_a_specific_interpreter_version_.28via_preferences_file.29
https://stackoverflow.com/questions/52046845/changing-the-python-interpreter-for-inkscape

**Comment by kubaraczkowski** [comment]
On MacOS BigSur and Inkscape 1.0.1 what I had to do is to install the 'prerequisities' that are normally installed by install_osx.py using the python3 embedded in the Inkscape package itself.
For me that was at `/Applications/Inkscape.app/Contents/Resources/bin/python3` so doing `-m pip install lxml pyusb libusb1` did it.

It still didn't want to load libusb because of 
OSError: dlopen(/usr/local/lib/libusb-1.0.dylib, 6): no suitable image found.  Did find:
	/usr/local/lib/libusb-1.0.dylib: code signature in (/usr/local/lib/libusb-1.0.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.

ayayay :/

**Comment by jtebert** [comment]
> On MacOS BigSur and Inkscape 1.0.1 what I had to do is to install the 'prerequisities' that are normally installed by install_osx.py using the python3 embedded in the Inkscape package itself.
> For me that was at `/Applications/Inkscape.app/Contents/Resources/bin/python3` so doing `-m pip install lxml pyusb libusb1` did it.
> 
> It still didn't want to load libusb because of
> OSError: dlopen(/usr/local/lib/libusb-1.0.dylib, 6): no suitable image found. Did find:
> /usr/local/lib/libusb-1.0.dylib: code signature in (/usr/local/lib/libusb-1.0.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
> 
> ayayay :/

Have you been able to find a solution to this? I don't fully understand Mac's security and Python paths (I'm typically on Linux), so I'm not sure how to approach solving this problem. Is there a way to get Inkscape to use the brew Python path?

**Comment by tschamm** [comment]
I assume there's a mismatch of the dylib version installed (via `brew install libusb`) and the libusb python packages compiled against another dylib version (for the one used in Inkscape as well as python provided by the system). Inkscape provides its own python3 (currently 3.8.5), Mac OS python3 is 3.5, homebrew currently provides 3.8.7 as well as 3.9.1.

So I suggest installing python3 via homebrew (brew is already necessary for libusb), install the necessary dependencies with pip3 (that is pip provided by brew) and update the extension preferences to use brew's python3.

Edit: I would not recommend to change the system provided python, using brew you won't need sudo at all.
