### ISSUE TITLE
Cannot run zadig-2.3.exe as Silhouette does not install driver

### ISSUE THREAD

**Issue by alan-rpi** [fablabnbg/inkscape-silhouette#83]
WIndows 7 Professional SP1 64 bit with silhouette-studio_v4.2.471 and zadig-2.4 

Having just bought a Silhouette Portrait 2 and using Inkscape this utility looks very useful, especially as Silhouette Studio (free version) is not seeing any content in a DXF test file.

I installed the silhouette-studio_v4.2.471 software but skipped installing Bonjour. 

When I plug in my Silhouette Portrait 2  Windows recognises the devices (but only on USB2 port) and then fails to install a driver.  This page https://www.silhouetteamerica.com/faq/solution/driver-concern says a driver is not needed and sure enough on starting Silhouette Studio it says it recognised the Portrait 2 (not yet tested the link).

When I run zadig-2.4 the list of devices is completely blank. That's presumably because no driver is installed. 

So how can I proceed with zadig when there is no driver and no driver is needed or provided by Silhouette?

Thanks for reading.
Alan
PS In the Read Me page it says under Windows to download zadig from http://zadig.akeo.ie/downloads/zadig-2.3.exe   That has changed and the link is now http://zadig.akeo.ie

**Comment by miLORD1337** [comment]
Did you click "List all devices" first?
EDIT: Oh, just seen how old this is... Sorry.

**Comment by t0b3** [comment]
fixed trough #123
