### ISSUE TITLE
Repo summary is misleading

### ISSUE THREAD

**Issue by Moini** [fablabnbg/inkscape-silhouette#86]
Hi :)

"An extension to drive a Silhoutte Cameo from within inkscape." seems to suggest that this is only for a Silhouette Cameo. However, the description in the README lists quite a few more devices.  Maybe the short description could be updated to reflect that progress?

**Comment by jnweiger** [comment]
Maybe like this:

"An extension to drive Silhoutte cutters (e.g. Cameo, Portrait series) from within inkscape."

Please reopen, if I got that wrong.

**Comment by Moini** [comment]
Danke!

**Comment by Moini** [comment]
Almost: there's an 'e' missing in the brand name (Silhouette)
