### ISSUE TITLE
We need a developer manual for the Cameo 4. Is there one?

### ISSUE THREAD

**Issue by Twanawebtech** [fablabnbg/inkscape-silhouette#87]
Thanks

**Comment by jnweiger** [comment]
I don't think one exists in the wild. I'd be happy to see one, too.
All development here is based on trial and error, USB snooping and educated guesswork. And then finally documentation was published for Cameo 3 -- but that is all we have: https://github.com/fablabnbg/inkscape-silhouette/issues/72

Please reopen, if there are any pointers to public developer documentation.

**Comment by FlyingSamson** [comment]
I have a Cameo 4 sitting around here und would be willing/interested in extending the plugin to that device, could you offer some guidance as to what would be the necessary steps? I already recorded some communications between the Cameo and Silhouette Studio using Wireshark and it looks pretty much like the commands the plugin would generate (aside from the BE-commands). But I presume it is not as simple as adding it to the DEVICE list with the appropriate product id and correct width as there are multiple places of the form `s.product_id() == PRODUCT_ID_SILHOUETTE_CAMEO3`. Any pointers on where to start would be greatly appreciated.

Maybe it would also make sense to work with classes derived from an abstract base class defining the required functionalities to avoid growing the `if ... elif ... else...` blocks for each new device added?
