### ISSUE TITLE
Rounded Rectangle Not Cutting Round

### ISSUE THREAD

**Issue by ManagedLoophole** [fablabnbg/inkscape-silhouette#91]
When I create a rectangle in inkscape with rounded corners, my Silhouette Cameo always cuts sharp corners no matter what.

Is there a setting or step I am missing?

**Comment by EtherGraf** [comment]
I am not sure if this conversion should get done automtatically by the extension.

But it should always work to manually convert all non-path objects to a path before plotting.
Use menu entry Path/Convert object to path.

**Comment by ManagedLoophole** [comment]
That did the trick. I knew I was missing something.

Thanks!!
