### ISSUE TITLE
Cuts first path then just loops

### ISSUE THREAD

**Issue by MagpieRH** [fablabnbg/inkscape-silhouette#92]
Hi all,
New to vinyl cutting and took me all day to setup my Silhouette Portrait 2 (got there in the end!) but still having an issue with it.

When cutting, it takes the first item and cuts it perfectly, then starts again and just loops over that one item. I have to turn it off to stop it. Inkscape gives me the following error message:
--------------------------------------
Traceback (most recent call last):
  File "sendto_silhouette.py", line 1236, in <module>
    e.affect()
  File "/usr/share/inkscape/extensions/inkex.py", line 281, in affect
    self.effect()
  File "sendto_silhouette.py", line 1175, in effect
    regoriginx=self.options.regoriginx,regoriginy=self.options.regoriginy)
  File "/usr/share/inkscape/extensions/silhouette/Graphtec.py", line 1003, in plot
    s.safe_write(p)
  File "/usr/share/inkscape/extensions/silhouette/Graphtec.py", line 387, in safe_write
    while not s.status() == "ready":
  File "/usr/share/inkscape/extensions/silhouette/Graphtec.py", line 430, in status
    s.write("\x1b\x05")
  File "/usr/share/inkscape/extensions/silhouette/Graphtec.py", line 365, in write
    raise ValueError('write %d bytes failed: r=%d' % (len(chunk), r))
ValueError: write 2 bytes failed: r=0
----------------------------------

Is there anything I need to change, be it a setting in the export to Silhouette dialogue (although I've left everything as standard; I did change the speed/pressure settings initially but have changed them back to 0,0,-1) or some of the code?

Many thanks, and thanks for the extension - I couldn't use my cutter without it!

**Comment by EtherGraf** [comment]
Never heard of such an failure.
There is a setting in the extensions at the options tab, "repeat each stroke". With this each of the strokes could be repeated N times. This should be set to "1" normally.

I am not sure if the write error has something to do with it.

Which versions of inkscape and extension are you using?
Which operating system?

**Comment by MagpieRH** [comment]
Quite willing to accept I may be the issue! Would just love to know how to sort it.

I wonder if it is just that the repeats is set to more than 1 - I haven't changed that setting but I will check it next time I'm in. I've been turning the cutter off to stop it, so maybe that's throwing the error.

I'm on Opensuse Leap (the latest stable release, 15.something I think), most up to date Inkscape available and only downloaded the extension this week so that should be the latest version as well.

Thank you for your input, I'll let you know if that solves it once I've had a chance to test it.

**Comment by MagpieRH** [comment]
Update:
'Repeat each stroke' setting is '1', as default. Everything else is, I think, default as well.

OS Opensuse Leap 15.1
Inkscape v0.92
Inkscape-Silhouette v1.2.1

Any other things I could check?

**Comment by EtherGraf** [comment]
The error message comes up highly probably because you have interrupted the plotter. I don't think it tells us any reasonable information.

Possibly there is something wrong with your inkscape document?
Does there the same path exist multiple times, e.g. invisible overlayed?

Try starting with a new document containing only a simple path, maybe a single rectangle.

Just as a hint: 
For further testing you should remove the blade to not damage anything by continuous cutting.

**Comment by MagpieRH** [comment]
Thank you, I'll try that, although it's had the same issue with 3 different paths so far: one large image (4" x 4"), an image of some text (converted to path - it's a google font that I had to take a screencap of) and smaller versions of both.

Bit perplexed really, and I don't have anything to run the official software on to see if it's a machine issue. Will keep trying!

Edit: Just tried again, with trace png files, it loops. With a simple object drawn in inkscape (I used a star), it cut once and then moved on to the next copy.

Seems your hunch about invisible overlays might be on the money. I'll have a look through the inkscape manual to see how I can see/edit the number of paths. Thanks for your help!

**Comment by EtherGraf** [comment]
Glad to be able to help you.

To get started:
You can see the document structure with menu entry Edit/XML-Editor...
There you can see the document tree. If you open the group nodes you can see the single paths.

Try to ungroup the groups, then you can move the single paths around.

Or you can merge the paths with Path/Merge Path... (Strg++, have no english menus here) to get a single path.
