### ISSUE TITLE
windows install

### ISSUE THREAD

**Issue by pierred35** [fablabnbg/inkscape-silhouette#93]
Hi, 
I'm sure I'm pretty close to succeed the installation after few hours... Thanks for your help. 
1) from  inkscape-silhouette-master folder, the 3 files are copied C:\Program Files\Inkscape\share\extensions 
2) from  libusb-win32-bin-1.2.6.0.zip\libusb-win32-bin-1.2.6.0\bin\x86 folder, the libusb0_x86.dll has been renamed to libusb0.dll and copy inside Windows\syswow64\libusb0.dll and also Windows\system32\libusb0.dll
3) Python has been installed
4) installed pyusb and pywinusb using pip install command
5) started inkscape --> no module named usb.com  COOL i'm pretty close
6) delete inkscape\python folder and restarted inkscape
--> could not find plateform independent libraries... ImportError: No module named site

I'm disappointed. Can you tell me what I did bad. Thanks a log

**Comment by t0b3** [comment]
@pierred35 is this issue solved?

**Comment by pierred35** [comment]
Yes, it has worked this weekend. 
Tank you for your support
