### ISSUE TITLE
Install package in Ubuntu 20.04 (Focal Fossa)

### ISSUE THREAD

**Issue by alsofiev** [fablabnbg/inkscape-silhouette#95]
Can't install python-usb package in Ubuntu 20.04 (Focal Fossa). Package not found.

**Comment by t0b3** [comment]
you may want to use [python3-usb](https://packages.ubuntu.com/focal/python3-usb) once you use inkscape >= 0.92.5
for inkscape <= 0.92.4 you still need [python-usb](https://packages.ubuntu.com/focal/python-usb) which is still available for focal

**Comment by alsofiev** [comment]
I added "universe" to /etc/apt/sources.list Everything works now
