### ISSUE TITLE
Autoblade issue, and adding defaults

### ISSUE THREAD

**Issue by MagpieRH** [fablabnbg/inkscape-silhouette#97]
Got the app working really well following some initial hiccups, but still having a couple of minor problems:

Autoblade settings seem to have no effect - it makes no effort to change the blade setting itself, and remains at whatever it's been set to manually. (Portrait 2, OpenSuse Leap 15, Inkscape 0.92.2, latest version of the plugin)

[question about adding default values for media. Found the bit in the source]

Thanks in advance

**Comment by t0b3** [comment]
@MagpieRH you are welcome to retry with the latest version
